// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
import { ILesson } from '@cirrus/models';

export const testDataReccurent853b: ILesson = {
  id: 853,
  lesson_type: 2,
  order: 0,
  system_name: 'Lesson 1 - VFR Recurrent',
  subtitle: '',
  thumbnail_image_url: '',
  mobile_hero_image_url: '',
  desktop_hero_image_url: '',
  title: 'Lesson 1',
  system_desc: 'The first lesson of the VFR Recurrent Course.',
  overview:
    '\u003cdiv\u003e\u003cb\u003eFlight Lesson\u003c/b\u003e\u003c/div\u003e\u003cdiv\u003eEstimated Lesson Time: .5 Hours Ground Training / 2.0 Hours Flight Training\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cimg src="https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/images/232ff18fcd2c83dfff90550e10338cREGULAR_maneuvers_abnormal_specialty_CAPS.png"\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cimg src="https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/images/b5cdf3883434fb23f27861088a8e81KEY_normManSpecAbnorm.png"\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cdiv\u003e\u003cb\u003eLesson Overview\u003c/b\u003e\u003c/div\u003e\u003cdiv\u003eThe flight portion will examine your competency flying as pilot-in-command under VFR. Your instructor will take a passenger-like role, such that you should only expect mistakes that jeopardize the flight\'s safety to be corrected. Factors like managing distractions, maintaining situational awareness, and avoiding task saturation play essential roles in the overall outcome of this lesson.\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003eYou are required to act as pilot-in-command safely and without assistance from your instructor. Tasks are complete when you’re able to execute them within the completion standards without the assistance of your instructor. This flight will need to be repeated if you do not meet the standards for any task.\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003eTasks being introduced for the first time are indicated in \u003cb\u003eBOLD\u003c/b\u003e. Tasks indicated as PERFORM must be performed without assistance from your instructor, as pilot-in-command.\u003c/div\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cimg src="https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/images/ed3439d5961b2db61514207ebf978aVFR_RECURRENT-L1.png"\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e',
  is_archived: false,
  is_preview: false,
  contents_are_linear: false,
  major_version: 1,
  minor_version: 2,
  updated_at: '2020-06-08T17:59:04.965Z',
  overview_image_url: '',
  student_intro_video: {
    content: {
      blob_directory: '',
      order: 0,
      quiz: '',
      content_tasks: [],
      progress: { id: 1, status: 'not_completed' },
      content_file: '',
      content_filename: '',
      content_html: '',
      content_type: 0,
      created_by: 'Cirrus Aircraft',
      desc: 'Perspective & Perspective+ Avionics Course',
      id: 401,
      jet_scoring: false,
      meta_tags: [],
      placeholder_image:
        'https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/content-files/5c480eb38443724475091bf0d91ba12.2.png',
      score: 0,
      show_comments: true,
      starter_file: '',
      subtitle: 'Hello Cockpit [2.1]',
      title: 'Hello Cockpit [2.1]',
      upload_image: '',
      url: '309005652',
    },

    content_id: 401,
    hidden: false,
    required: false,
    id: 1,
    title: '',
    updated_at: '',
    created_at: '',
  },
  instructor_intro_video: {
    content: {
      blob_directory: '',
      order: 0,
      quiz: '',
      content_tasks: [],
      progress: { id: 1, status: 'not_completed' },
      content_file: '',
      content_filename: '',
      content_html: '',
      content_type: 0,
      created_by: 'Cirrus Aircraft',
      desc: 'Perspective & Perspective+ Avionics Course',
      id: 401,
      jet_scoring: false,
      meta_tags: [],
      placeholder_image:
        'https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/content-files/5c480eb38443724475091bf0d91ba12.2.png',
      score: 0,
      show_comments: true,
      starter_file: '',
      subtitle: 'Hello Cockpit [2.1]',
      title: 'Hello Cockpit [2.1]',
      upload_image: '',
      url: '309005652',
    },
    content_id: 401,
    created_at: '2022-05-18T15:55:59.249Z',
    hidden: false,
    id: 69,
    required: false,
    title: 'hello',
    updated_at: '2022-05-18T15:55:59.249Z',
  },
  contents: [
    {
      id: 684,
      order: 0,
      title: 'Lesson 1 Instructor Assessment',
      subtitle: 'Lesson 1 Instructor Assessment',
      score: 0,
      url: '',
      meta_tags: [],
      content_tasks: [],
      quiz: null,
      content_type: 11,
      desc: 'VFR Recurrent Course: Flight Lesson\nEstimated Lesson Time: .5 Hour Ground Training / 1.8 Hours Flight Training \n\n\nNormal (PERFORM)\n- Aircraft Weight and Balance, Aircraft Performance, Preflight Assessment, Engine Start, Taxiing, Before Takeoff Check, Normal Takeoff, Climb, Cruise, Descent, Traffic Pattern, Normal Landing, and After Landing, Parking and Securing\n\nManeuvers (PERFORM)\n- Slow Flight, Power-Off Stalls, Power-On Stalls, and Steep Turn\n\nAbnormals (PERFORM)\n- Unusual Attitudes, and Engine Malfunction\n\nSpecialty (PERFORM)\n- Short-Field Takeoff, Short-Field Landing, Flaps 0 and 50% Landing, and Go-Around\n\nSimulated CAPS Deployment (PERFORM ONE)\n- Engine Failure on Takeoff, Loss of Control, Spin Recovery, Structural Failure, Midair Collision, Engine Failure in Cruise (Runway within Glide), Engine Failure in Cruise (Runway not within Glide), Engine Failure in IMC, and Severe Icing',
      content_file: '',
      placeholder_image: '',
      jet_scoring: false,
      content_html: '',
      created_by: 'Cirrus Aircraft',
      upload_image:
        'https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/images/7f5828d0bdf522989e57689f251e5bREGULAR_maneuvers_abnormal_specialty_CAPS.png',
      content_filename: '',
      starter_file: '',
      blob_directory: '',
      show_comments: true,
      progress: {
        id: 0,
        status: 'not_started',
      },
    },
  ],
  instructor_overview: '',
  instructor_contents: [],
  progress: {
    id: 0,
    status: 'not_started',
  },
  course_id: 0,
  course_attempt_id: 0,
  stage_id: 0,
  progress_stats: [],
};
