// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
import { ILesson } from '@cirrus/models';

export const testDataReccurent853: ILesson = {
  id: 853,
  lesson_type: 2,
  order: 0,
  system_name: 'Lesson 1 - VFR Recurrent',
  title: 'Lesson 1',
  system_desc: 'The first lesson of the VFR Recurrent Course.',
  overview:
    '\u003cdiv\u003e\u003cb\u003eFlight Lesson\u003c/b\u003e\u003c/div\u003e\u003cdiv\u003eEstimated Lesson Time: .5 Hours Ground Training / 2.0 Hours Flight Training\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cimg src="https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/images/232ff18fcd2c83dfff90550e10338cREGULAR_maneuvers_abnormal_specialty_CAPS.png"\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cimg src="https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/images/b5cdf3883434fb23f27861088a8e81KEY_normManSpecAbnorm.png"\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cdiv\u003e\u003cb\u003eLesson Overview\u003c/b\u003e\u003c/div\u003e\u003cdiv\u003eThe flight portion will examine your competency flying as pilot-in-command under VFR. Your instructor will take a passenger-like role, such that you should only expect mistakes that jeopardize the flight\'s safety to be corrected. Factors like managing distractions, maintaining situational awareness, and avoiding task saturation play essential roles in the overall outcome of this lesson.\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003eYou are required to act as pilot-in-command safely and without assistance from your instructor. Tasks are complete when you’re able to execute them within the completion standards without the assistance of your instructor. This flight will need to be repeated if you do not meet the standards for any task.\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003eTasks being introduced for the first time are indicated in \u003cb\u003eBOLD\u003c/b\u003e. Tasks indicated as PERFORM must be performed without assistance from your instructor, as pilot-in-command.\u003c/div\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cimg src="https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/images/ed3439d5961b2db61514207ebf978aVFR_RECURRENT-L1.png"\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e',
  is_archived: false,
  is_preview: false,
  contents_are_linear: false,
  major_version: 1,
  minor_version: 2,
  updated_at: '2020-06-08T17:59:04.965Z',
  overview_image_url: '',
  student_intro_video: '',
  instructor_intro_video: '',
  contents: [
    {
      id: 684,
      order: 0,
      title: 'Lesson 1 Instructor Assessment',
      subtitle: 'Lesson 1 Instructor Assessment',
      score: 0,
      url: '',
      meta_tags: [],
      content_tasks: [
        {
          id: 2049,
          task: {
            id: 12,
            name: 'Aircraft Weight and Balance',
            standards: [
              'KNOWLEDGE: Know and comply with the designed weight limitations applicable to the Cirrus.',
              'RISK: Assess and mitigate risks associated with the improper loading of the Cirrus.',
              'SKILL: Calculate weight and balance and identify and correct out-of-CG loading conditions.',
            ],
            task_category: {
              id: 17,
              name: 'Preflight Preparation',
              desc: '',
              created_at: '2018-07-27T13:08:55.513Z',
              updated_at: '2018-11-08T13:28:06.139Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 0,
          task_id: 12,
          task_type: 'perform',
        },
        {
          id: 2050,
          task: {
            id: 13,
            name: 'Aircraft Performance',
            standards: [
              'KNOWLEDGE: Understand the factors affecting performance, such as: atmospheric conditions, pilot technique, airplane configuration, airport environment, and weight and balance.',
              'KNOWLEDGE: Understand the potential difference between calculated and actual performance.',
              'SKILL: Accurately determine the expected performance of the Cirrus by using the appropriate charts.',
            ],
            task_category: {
              id: 17,
              name: 'Preflight Preparation',
              desc: '',
              created_at: '2018-07-27T13:08:55.513Z',
              updated_at: '2018-11-08T13:28:06.139Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 1,
          task_id: 13,
          task_type: 'perform',
        },
        {
          id: 2051,
          task: {
            id: 14,
            name: 'Preflight Assessment',
            standards: [
              'KNOWLEDGE: Describe which items must be inspected during preflight, why each item is checked, how to identify possible defects, and any applicable regulations.',
              'KNOWLEDGE: Recognize and understand environmental factors affecting the flight, such as: weather, terrain, route, and obstructions.',
              'KNOWLEDGE: Define your personal minimums and explain how they are applied to the flight.',
              'SKILL: Confirm that the Cirrus is safe for flight using the appropriate checklist.',
            ],
            task_category: {
              id: 17,
              name: 'Preflight Preparation',
              desc: '',
              created_at: '2018-07-27T13:08:55.513Z',
              updated_at: '2018-11-08T13:28:06.139Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 2,
          task_id: 14,
          task_type: 'perform',
        },
        {
          id: 2052,
          task: {
            id: 15,
            name: 'Engine Start',
            standards: [
              'KNOWLEDGE: Describe starting the Cirrus under varying conditions, such as cold start and hot start.',
              'KNOWLEDGE: Identify the symptoms of, and describe the procedure for, starting a flooded engine.',
              'RISK: Demonstrate that you can assess and mitigate the risks associated with the propeller and the propeller safety area.',
              'SKILL: Position the Cirrus properly for a safe start using the appropriate checklist.',
              'SKILL: Complete the appropriate checklist.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 3,
          task_id: 15,
          task_type: 'perform',
        },
        {
          id: 2053,
          task: {
            id: 16,
            name: 'Taxiing',
            standards: [
              'KNOWLEDGE: Identify and understand airport markings, signs, and lights.',
              'KNOWLEDGE: Identify and describe various indicators for estimating wind direction and velocity.',
              'RISK: Assess and mitigate risks associated with distractions during taxi and ground operations.',
              'RISK: Assess and mitigate risks associated with taxi route confirmation bias.',
              'RISK: Assess and mitigate risks associated with last minute taxi route or departure runway changes.',
              'SKILL: Communicate with, and follow instructions from, air traffic control (if applicable).',
              'SKILL: Confirm proper brake operation by completing a brake check immediately after beginning movement.',
              'SKILL: Navigate the airport and maintain situational awareness by using an airport diagram or taxi chart.',
              'SKILL: Maintain positive control of the Cirrus during all ground operations.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 4,
          task_id: 16,
          task_type: 'perform',
        },
        {
          id: 2054,
          task: {
            id: 17,
            name: 'Before Takeoff Check',
            standards: [
              'KNOWLEDGE: Understand and describe the pre-takeoff checklist, why each item is checked, and how to detect possible malfunctions and abnormalities.',
              'RISK: Identify the potential for and describe/execute strategies to mitigate the risks associated with wake turbulence.',
              'SKILL: Position the Cirrus considering wind, other aircraft, and hazards. ',
              'SKILL: Complete the appropriate checklist.',
              'SKILL: Divide attention both inside and outside of the Cirrus.',
              'SKILL: Conduct a takeoff briefing and review takeoff performance and CAPS strategy.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 5,
          task_id: 17,
          task_type: 'perform',
        },
        {
          id: 2055,
          task: {
            id: 4,
            name: 'Normal Takeoff',
            standards: [
              'KNOWLEDGE: Understand the effects of atmospheric conditions on takeoff and climb performance.',
              'KNOWLEDGE: Understand VX and VY.',
              'RISK: Select the best runway based on pilot ability, expected performance, airplane limitations, available distance, and wind.',
              'RISK: Assess and mitigate the risks associated with: crosswind, windshear, tailwind, wake turbulence, various runway surfaces and conditions.',
              'RISK: Establish a strategy for CAPS deployment during takeoff and climb.',
              'RISK: Establish a plan for a rejected takeoff or engine failure during the takeoff or climb phase.',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'SKILL: Confirm takeoff power and proper engine and flight instrument indications prior to rotation.',
              'SKILL: Rotate at POH recommended airspeed.',
              'SKILL: Maintain airspeed +10/-5 kts.',
              'SKILL: Retract flaps after establishing a positive rate of climb, clear of terrain, and above flap retraction airspeed.',
              'SKILL: Maintain directional control and proper wind-drift correction throughout takeoff and climb.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 6,
          task_id: 4,
          task_type: 'perform',
        },
        {
          id: 2056,
          task: {
            id: 28,
            name: 'Enroute Climb',
            standards: [
              'KNOWLEDGE: Understand the relationship of power setting and airspeed and the impact on engine cooling.',
              'KNOWLEDGE: Understand VX and VY.',
              'KNOWLEDGE: Understand cruise climb airspeed.',
              'RISK: Identify collision hazards during low altitude maneuvering and climb.',
              'SKILL: Maintain airspeed +10/-5 kts. ',
              'SKILL: Maintain directional control and proper wind-drift correction.',
              'SKILL: Complete the appropriate checklist.',
              'SKILL: Use proper engine cooling techniques.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 7,
          task_id: 28,
          task_type: 'perform',
        },
        {
          id: 2057,
          task: {
            id: 18,
            name: 'Cruise',
            standards: [
              'KNOWLEDGE: Understand how to select an appropriate route and altitude for the flight.',
              'RISK: Demonstrate the ability prioritize tasks and minimize distractions. ',
              'SKILL: Maintain altitude +/-200 ft and heading +/-15°.',
              'SKILL: Complete the appropriate checklist.',
              'SKILL: Use the appropriate mixture leaning procedure as described in the POH.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 8,
          task_id: 18,
          task_type: 'perform',
        },
        {
          id: 2058,
          task: {
            id: 39,
            name: 'Slow Flight',
            standards: [
              'KNOWLEDGE: Understand the aerodynamics associated with maneuvering during slow flight.',
              'RISK: Identify risks associated with inadvertent slow flight.',
              'RISK: Identify risks associated to the range and limitations of stall warning system.',
              'RISK: Identify risks associated with uncoordinated flight.',
              'RISK: Assess and mitigate risks associated with atmospheric and environmental conditions such as turbulence, microbursts, and high-density altitudes.',
              'RISK: Divide attention between aircraft control and orientation.',
              'SKILL: Maintain altitude +/-100 ft; airspeed +10/-0 kts; bank +/-10°; and heading +/-10°.',
              'SKILL: Select an entry altitude that allows the maneuver to be completed no lower than 1,500 feet AGL.',
              'SKILL: Accomplish coordinated straight-and-level flight, turns, climbs, and descents with flap configurations specified by the instructor.',
              'SKILL: Establish and maintain an airspeed at which any further increase in angle of attack, increase in load factor, or reduction in power, would result in a stall warning. ',
            ],
            task_category: {
              id: 21,
              name: 'Maneuver',
              desc: '',
              created_at: '2018-07-27T13:25:07.919Z',
              updated_at: '2018-07-27T13:28:05.370Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 9,
          task_id: 39,
          task_type: 'perform',
        },
        {
          id: 2059,
          task: {
            id: 40,
            name: 'Power-Off Stalls',
            standards: [
              'KNOWLEDGE: Understand aerodynamics associated with stalls in various configurations.',
              'KNOWLEDGE: Understand the stall characteristics of your Cirrus and how to identify impending and full stall indications.',
              'KNOWLEDGE: Understand the fundamentals of stall recovery.',
              'RISK: Identify the factors and situations that can lead to an inadvertent power-off stall, spin, and loss of control.',
              'RISK: Identify risks associated to the range and limitations of stall warning system.',
              'RISK: Identify the risks associated with not recognizing and recovering at the first indication of stall.',
              'RISK: Identify the risks associated with using an improper stall recovery procedure.',
              'RISK: Assess and mitigate the risks associated with secondary stalls, accelerated stalls, and cross-controlled stalls.',
              'RISK: Assess and mitigate risks associated with atmospheric and environmental conditions such as turbulence, microbursts, and high-density altitudes.',
              'RISK: Divide attention between aircraft control and orientation.',
              'SKILL: Maintain bank +/-10°; if turning, and heading +/-10°; if in straight flight.',
              'SKILL: Select an entry altitude that allows the maneuver to be completed no lower than 1,500 feet AGL.',
              'SKILL: Acknowledge cues of the impending stall and then recover promptly after an impending or full stall has occurred.',
              'SKILL: Execute a stall recovery in accordance with procedures set forth in the POH.',
              'SKILL: Return to the altitude, heading, and airspeed specified by the instructor/evaluator.',
            ],
            task_category: {
              id: 21,
              name: 'Maneuver',
              desc: '',
              created_at: '2018-07-27T13:25:07.919Z',
              updated_at: '2018-07-27T13:28:05.370Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 10,
          task_id: 40,
          task_type: 'perform',
        },
        {
          id: 2060,
          task: {
            id: 41,
            name: 'Power-On Stall',
            standards: [
              'KNOWLEDGE: Understand aerodynamics associated with stalls in various configurations.\n',
              'KNOWLEDGE: Understand the stall characteristics of your Cirrus and how to identify impending and full stall indications.',
              'KNOWLEDGE: Understand the fundamentals of stall recovery.',
              'RISK: Identify the factors and situations that can lead to an inadvertent power-on stall, spin, and loss of control.',
              'RISK: Identify risks associated to the range and limitations of stall warning system.',
              'RISK: Identify the risks associated with not recognizing and recovering at the first indication of stall.',
              'RISK: Identify the risks associated with using an improper stall recovery procedure.',
              'RISK: Assess and mitigate the risks associated with secondary stalls, accelerated stalls, and cross-controlled stalls.',
              'RISK: Assess and mitigate risks associated with atmospheric and environmental conditions such as turbulence, microbursts, and high-density altitudes.',
              'RISK: Divide attention between aircraft control and orientation.',
              'SKILL: Maintain bank +/-10°; if turning, and heading +/-10°; if in straight flight.',
              'SKILL: Select an entry altitude that allows the maneuver to be completed no lower than 1,500 feet AGL.',
              'SKILL: Acknowledge the cues of the impending stall and then recover promptly after an impending or full stall occurs.',
              'SKILL: Execute a stall recovery in accordance with procedures set forth in the POH.',
              'SKILL: Return to the altitude, heading, and airspeed specified by the instructor/evaluator.',
            ],
            task_category: {
              id: 21,
              name: 'Maneuver',
              desc: '',
              created_at: '2018-07-27T13:25:07.919Z',
              updated_at: '2018-07-27T13:28:05.370Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 11,
          task_id: 41,
          task_type: 'perform',
        },
        {
          id: 2061,
          task: {
            id: 37,
            name: 'Steep Turn',
            standards: [
              'KNOWLEDGE: Understand the aerodynamics associated with steep turns.',
              'RISK: Divide attention between aircraft control and orientation.',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'RISK: Identify and mitigate the risks associated with uncoordinated flight.',
              'SKILL: Maintain altitude +/-100 ft; airspeed +/-10 kts; bank +/-5°; and rollout heading +/-10° from entry heading.',
              'SKILL: Establish recommended airspeed.',
              'SKILL: Roll into a coordinated 360° steep turn with approximately a 45° (Private Pilot) or 50° (Commercial Pilot) bank.',
            ],
            task_category: {
              id: 21,
              name: 'Maneuver',
              desc: '',
              created_at: '2018-07-27T13:25:07.919Z',
              updated_at: '2018-07-27T13:28:05.370Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 12,
          task_id: 37,
          task_type: 'perform',
        },
        {
          id: 2062,
          task: {
            id: 43,
            name: 'Unusual Flight Attitudes',
            standards: [
              'KNOWLEDGE: Understand the procedure for recovering from unusual attitudes.',
              'KNOWLEDGE: Understand situations and factors that contribute to unusual attitudes.',
              'RISK: Identify risks associated with situations that lead to loss of control or unusual flight attitudes.\n',
              'RISK: Identify risks associated with not recognizing or following the proper recovery procedure for unusual flight attitudes.',
              'SKILL: Cross-check and identify an unusual attitude and apply the proper recovery.',
              'SKILL: Use smooth, correct, and coordinated control inputs to recover while staying within the airplane’s limitations and flight parameters.',
            ],
            task_category: {
              id: 21,
              name: 'Maneuver',
              desc: '',
              created_at: '2018-07-27T13:25:07.919Z',
              updated_at: '2018-07-27T13:28:05.370Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 13,
          task_id: 43,
          task_type: 'perform',
        },
        {
          id: 2063,
          task: {
            id: 46,
            name: 'Engine Malfunction',
            standards: [
              'KNOWLEDGE: Understand engine operation and indications.',
              'KNOWLEDGE: Understand possible engine malfunctions.',
              'RISK: Identify the risks associated with using the incorrect checklist for an engine malfunction.',
              'RISK: Assess and mitigate risks associated with an engine malfunction at low altitudes.',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'SKILL: Maintain airspeed +/- 10 kts.',
              'SKILL: Recognize an engine malfunction and maintain control.',
              'SKILL: Demonstrate good situational awareness and systems knowledge. ',
              'SKILL: Execute the appropriate checklist.',
              'SKILL: Describe the CAPS deployment strategy for an engine malfunction.',
            ],
            task_category: {
              id: 19,
              name: 'Abnormal Procedure',
              desc: '',
              created_at: '2018-07-27T13:24:20.067Z',
              updated_at: '2018-07-27T13:24:20.067Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 14,
          task_id: 46,
          task_type: 'perform',
        },
        {
          id: 2064,
          task: {
            id: 29,
            name: 'Descent',
            standards: [
              'KNOWLEDGE: Understand how to select the desired landing runway by considering winds, performance, and other traffic in the area.',
              'KNOWLEDGE: Understand and explain right-of-way rules.',
              'RISK: Identify collision hazards during descent and low altitude maneuvering.',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'SKILL: Maintain altitude +/-200 ft and assigned heading +/-15°.',
              'SKILL: Maintain proper airspeed for environmental conditions.',
              'SKILL: Maintain situational awareness and prepare for arrival into the terminal area. ',
              'SKILL: Complete the appropriate checklist.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 15,
          task_id: 29,
          task_type: 'perform',
        },
        {
          id: 2065,
          task: {
            id: 19,
            name: 'Traffic Pattern',
            standards: [
              'KNOWLEDGE: Understand and explain right-of-way rules.',
              'KNOWLEDGE: Understand towered versus non-towered airport operations.',
              'RISK: Identify the potential for and describe/execute strategies to mitigate the risks associated with wake turbulence.',
              'RISK:  Demonstrate the ability to prioritize tasks and minimize distractions.',
              'SKILL: Maintain traffic pattern altitude +/-100 ft and airspeed +/-10 kts.',
              'SKILL: Follow recommended traffic pattern procedures and maintain situational awareness and proper spacing from other aircraft in the traffic pattern.',
              'SKILL: Correct for wind drift to maintain the proper ground track.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 16,
          task_id: 19,
          task_type: 'perform',
        },
        {
          id: 2066,
          task: {
            id: 20,
            name: 'Normal Landing',
            standards: [
              'KNOWLEDGE: Understand the effect of atmospheric conditions on approach and landing performance.',
              'KNOWLEDGE: Understand the elements of a stabilized approach.',
              'KNOWLEDGE: Understand wind correction techniques.',
              'RISK: Assess and mitigate the risks associated with: crosswind, windshear, tailwind, wake turbulence, various runway surfaces and conditions.',
              'RISK: Assess and mitigate the risks associated with land and hold short operations (LAHSO).',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'SKILL: Maintain approach airspeed, +10/-5 knots, or as recommended for gust velocity.',
              'SKILL: Complete the appropriate checklists and establish the proper configuration to maintain a stabilized approach.',
              'SKILL: Align with the correct/assigned runway.',
              'SKILL: Maintain directional control and proper wind-drift correction throughout the landing and roll-out.',
              'SKILL: Touch down within 400 feet beyond a specified point.',
              'SKILL: Touch down slightly above stall.',
              'SKILL: Touch down with no appreciable drift.',
              'SKILL: Touch down with the longitudinal axis aligned with the centerline.',
              'SKILL: Execute a timely go-around if an unsafe approach or landing may result.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 17,
          task_id: 20,
          task_type: 'perform',
        },
        {
          id: 2067,
          task: {
            id: 34,
            name: 'Short-Field Takeoff',
            standards: [
              'KNOWLEDGE: Understand the effects of atmospheric conditions on takeoff and climb performance. \n',
              'KNOWLEDGE: Understand VX and VY.',
              'RISK: Able to select the best runway based on pilot ability, expected performance, airplane limitations, available distance, and wind.',
              'RISK: Assess and mitigate the risks associated with: crosswind, windshear, tailwind, wake turbulence, various runway surfaces and conditions.',
              'RISK: Establish a strategy for CAPS deployment during takeoff and climb.',
              'RISK: Establish a plan for a rejected takeoff or engine failure during the takeoff or climb phase.',
              'RISK: Demonstrate the ability prioritize tasks and minimize distractions.',
              'SKILL: Maintain obstacle clearance airspeed +10/-5 kts until 50 ft, then Vx  +10/-5 kts.',
              'SKILL: Complete the appropriate checklists and properly configure your Cirrus for takeoff.',
              'SKILL: Maintain directional control and proper wind-drift correction throughout takeoff and climb.',
              'SKILL: Apply brakes while setting aircraft power to achieve maximum performance.',
              'SKILL: Confirm takeoff power and proper engine and flight instrument indications prior to rotation.',
            ],
            task_category: {
              id: 62,
              name: 'Specialty Procedures',
              desc: '',
              created_at: '2018-12-07T21:41:16.296Z',
              updated_at: '2018-12-07T21:41:16.296Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 18,
          task_id: 34,
          task_type: 'perform',
        },
        {
          id: 2068,
          task: {
            id: 32,
            name: 'Short-Field Landing',
            standards: [
              'KNOWLEDGE: Understand the effect of atmospheric conditions on approach and landing performance.',
              'KNOWLEDGE: Understand the elements of a stabilized approach.',
              'KNOWLEDGE: Understand wind correction techniques.',
              'RISK: Assess and mitigate the risks associated with: crosswind, windshear, tailwind, wake turbulence, and runway surface condition.',
              'RISK: Assess and mitigate the risks associated with land and hold short operations (LAHSO).',
              'RISK: Demonstrate the ability prioritize tasks and minimize distractions.',
              'SKILL: Maintain airspeed +10/-5 kts, or as recommended for gust velocity. ',
              'SKILL: Complete the appropriate checklists and establish the proper configuration to maintain a stabilized approach.',
              'SKILL: Align with the correct/assigned runway.',
              'SKILL: Maintain directional control and proper wind-drift correction throughout the landing and roll-out.',
              'SKILL: Touch down within 200 feet beyond a specified point.',
              'SKILL: Touch down slightly above stall.',
              'SKILL: Touch down with no appreciable drift.',
              'SKILL: Touch down with the longitudinal axis aligned with the centerline.',
              'SKILL: Perform maximum braking procedures.',
              'SKILL: Execute a timely go-around if an unsafe approach or landing may result.',
            ],
            task_category: {
              id: 62,
              name: 'Specialty Procedures',
              desc: '',
              created_at: '2018-12-07T21:41:16.296Z',
              updated_at: '2018-12-07T21:41:16.296Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 19,
          task_id: 32,
          task_type: 'perform',
        },
        {
          id: 2069,
          task: {
            id: 36,
            name: 'Flaps 50% or 0% Landing',
            standards: [
              'KNOWLEDGE: Understand the effect of atmospheric conditions on approach and landing performance.',
              'KNOWLEDGE: Understand the effects of flap configuration on approach angle and speed.',
              'KNOWLEDGE: Understand the elements of a stabilized approach.',
              'KNOWLEDGE: Understand wind correction techniques.',
              'RISK: Assess and mitigate the risks associated with: crosswind, windshear, tailwind, wake turbulence, and runway surface condition.',
              'RISK: Assess and mitigate the risks associated with land and hold short operations (LAHSO).',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'SKILL: Maintain airspeed +10/-5 kts, or as recommended for gust velocity. ',
              'SKILL: Complete the appropriate checklists and establish and maintain a stabilized approach.',
              'SKILL: Align with the correct/assigned runway.',
              'SKILL: Touch down within 400 feet beyond the specified point.',
              'SKILL: Touch down slightly above stall.',
              'SKILL: Touch down with no appreciable drift.',
              'SKILL: Touch down with the longitudinal axis aligned with the centerline.',
              'SKILL: Execute a timely go-around if an unsafe approach or landing may result.',
            ],
            task_category: {
              id: 62,
              name: 'Specialty Procedures',
              desc: '',
              created_at: '2018-12-07T21:41:16.296Z',
              updated_at: '2018-12-07T21:41:16.296Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 20,
          task_id: 36,
          task_type: 'perform',
        },
        {
          id: 2070,
          task: {
            id: 30,
            name: 'Go-Around',
            standards: [
              'KNOWLEDGE: Understand the effect of atmospheric conditions on approach and landing performance.\n',
              'KNOWLEDGE: Understand the elements of a stabilized approach.',
              'KNOWLEDGE: Understand wind correction techniques.',
              'RISK: Identify the risks associated with a delayed recognition of the need for a go-around/rejected landing.',
              'RISK: Identify the risks associated with reduced performance during a low altitude go-around/rejected landing.',
              'RISK: Understand the risks associated with improper power application and/or configuration during a go-around/rejected landing.',
              'RISK: Assess and mitigate the risks associated with stalls, spins, and CFIT.',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'SKILL: Transition to climb pitch attitude for VX or VY, maintain airspeed +10/-5 kts.',
              'SKILL: Apply takeoff power immediately.',
              'SKILL: Retract flaps after reaching positive rate of climb, clear of terrain/obstacles, and flaps retract speed.',
              'SKILL: Maintain directional control and proper wind-drift correction.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 21,
          task_id: 30,
          task_type: 'perform',
        },
        {
          id: 2071,
          task: {
            id: 22,
            name: 'After Landing, Parking and Securing',
            standards: [
              'KNOWLEDGE: Understand how to document in-flight and postflight discrepancies.',
              'RISK: Demonstrate the ability to prioritize tasks and minimize distractions.',
              'RISK: Assess and mitigate risks associated with taxi route confirmation bias.',
              'RISK: Assess and mitigate risks associated with disembarking passengers.',
              'SKILL: Safely and securely park your Cirrus and complete a thorough post-flight using the appropriate checklist.',
            ],
            task_category: {
              id: 18,
              name: 'Normal Procedure',
              desc: '',
              created_at: '2018-07-27T13:11:37.263Z',
              updated_at: '2018-07-27T13:24:27.499Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 22,
          task_id: 22,
          task_type: 'perform',
        },
        {
          id: 2072,
          task: {
            id: 96,
            name: 'Simulated CAPS Deployment',
            standards: [
              'KNOWLEDGE: Understand CAPS operation and limitations.',
              'RISK: Identify situations that necessitate using CAPS.',
              'RISK: Identify CAPS strategy during each phase of flight.',
              'RISK: Assess and mitigate risks associated with pilot incapacitation and non-crewmember deployment of CAPS.',
              'RISK: Demonstrate the ability prioritize tasks and minimize distractions.',
              'SKILL: Announce and adhere to CAPS deployment strategy.',
              'SKILL: Complete the appropriate checklist for CAPS deployment.',
              'SKILL: Demonstrate good situational awareness, division of attention, and proper planning. ',
              'SKILL: Complete post CAPS deployment procedures, when appropriate.',
            ],
            task_category: {
              id: 19,
              name: 'Abnormal Procedure',
              desc: '',
              created_at: '2018-07-27T13:24:20.067Z',
              updated_at: '2018-07-27T13:24:20.067Z',
            },
            is_archived: false,
          },
          content_id: 684,
          required_successful_attempts: 1,
          order: 23,
          task_id: 96,
          task_type: 'perform',
        },
      ],
      quiz: null,
      content_type: 9,
      desc: 'VFR Recurrent Course: Flight Lesson\nEstimated Lesson Time: .5 Hour Ground Training / 1.8 Hours Flight Training \n\n\nNormal (PERFORM)\n- Aircraft Weight and Balance, Aircraft Performance, Preflight Assessment, Engine Start, Taxiing, Before Takeoff Check, Normal Takeoff, Climb, Cruise, Descent, Traffic Pattern, Normal Landing, and After Landing, Parking and Securing\n\nManeuvers (PERFORM)\n- Slow Flight, Power-Off Stalls, Power-On Stalls, and Steep Turn\n\nAbnormals (PERFORM)\n- Unusual Attitudes, and Engine Malfunction\n\nSpecialty (PERFORM)\n- Short-Field Takeoff, Short-Field Landing, Flaps 0 and 50% Landing, and Go-Around\n\nSimulated CAPS Deployment (PERFORM ONE)\n- Engine Failure on Takeoff, Loss of Control, Spin Recovery, Structural Failure, Midair Collision, Engine Failure in Cruise (Runway within Glide), Engine Failure in Cruise (Runway not within Glide), Engine Failure in IMC, and Severe Icing',
      content_file: '',
      placeholder_image: '',
      jet_scoring: false,
      content_html: '',
      created_by: 'Cirrus Aircraft',
      upload_image: '',
      content_filename: '',
      starter_file: '',
      blob_directory: '',
      show_comments: true,
      progress: {
        id: 0,
        status: 'not_started',
      },
    },
  ],
  progress: {
    id: 0,
    status: 'in_progress',
  },
  instructor_overview: '',
  instructor_contents: [],
  course_id: 0,
  course_attempt_id: 0,
  stage_id: 0,
};
