// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
import { ILesson, ProgressStat, ProgressType } from '@cirrus/models';

const progressStats: ProgressStat[] = [
  {
    type: ProgressType.Ground,
    completed: 5,
    total: 10,
    status: 'in_progress',
  },
  {
    type: ProgressType.Flight,
    completed: 12,
    total: 20,
    status: 'in_progress',
  },
  {
    type: ProgressType.Simulator,
    completed: 10,
    total: 14,
    status: 'in_progress',
  },
  {
    type: ProgressType.Landings,
    completed: 9,
    total: 12,
    status: 'in_progress',
  },
  {
    type: ProgressType.Assessment,
    completed: 12,
    total: 20,
    status: 'in_progress',
  },
];

export const testData: ILesson = {
  id: 832,
  system_desc:
    'The SR Series Systems self-study lesson for flight training courses.',

  updated_at: '2020-02-14T20:21:44.256Z',
  subtitle: '',
  thumbnail_image_url: '',
  mobile_hero_image_url: '',
  desktop_hero_image_url: '',
  system_name: 'SR Series Systems Self Study Lesson - Flight Training Courses',
  lesson_type: 0,
  title: 'Systems',
  overview:
    "<div><b>Self-Study Lesson</b></div><div>Estimated Lesson Time: 2.0 Hours</div><div><br></div><div>Learning about the aircraft's systems is fundamental to transitioning into your Cirrus. This lesson is designed to better connect you with your Cirrus by developing a comprehensive understanding, from the inside out.&nbsp;</div><div><br></div>",
  is_archived: false,
  contents_are_linear: false,
  is_preview: false,
  major_version: 1,
  minor_version: 2,
  contents: [
    {
      id: 630,
      title: 'Primary Flight Controls',
      subtitle: 'Primary Flight Controls',
      score: 0,
      url: '377578235',
      content_type: 0,
      meta_tags: [],
      content_tasks: [],
      content_html: '',
      desc: 'Primary Flight Controls video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a84173672f8f9d5c5aa4dd32e91068Primary Flight Controls.png',
      content_file: '',
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: '',
      content_filename: '',
      blob_directory: '',
      starter_file: '',
      show_comments: true,
      order: 0,
      quiz: 0,
      progress: {
        id: 0,
        status: 'completed',
      },
    },
    {
      id: 631,
      title: 'Secondary Flight Controls ',
      subtitle: 'Secondary Flight Controls ',
      score: 0,
      url: '377578031',
      content_type: 0,
      meta_tags: [],
      content_tasks: [],
      content_html: '',
      desc: 'Secondary Flight Controls video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/3b7ad00c3fb97838bba10ac45f3d57Secondary Flight Controls.png',
      content_file: '',
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: '',
      content_filename: '',
      blob_directory: '',
      starter_file: '',
      show_comments: true,
      order: 1,
      quiz: 0,
      progress: {
        id: 0,
        status: 'not_started',
      },
    },
    {
      id: 632,
      title: 'Flight Controls & Trim: Controls, Operation, and Indications',
      subtitle: 'Flight Controls & Trim: Controls, Operation, and Indications',
      score: 0,
      url: '377578144',
      content_type: 0,
      meta_tags: [],
      content_tasks: [],
      content_html: '',
      desc: 'Flight Controls & Trim: Controls, Operation, and Indications video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/707a10514ac95bee353d6379d062dfControls, Operation, and Indications.png',
      content_file: '',
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: '',
      content_filename: '',
      blob_directory: '',
      starter_file: '',
      show_comments: true,
      order: 2,
      quiz: 0,
      progress: {
        id: 0,
        status: 'in_progress',
      },
    },
  ],
  order: 0,
  overview_image_url: '',
  student_intro_video: {
    content: {
      blob_directory: '',
      order: 0,
      quiz: '',
      content_tasks: [],
      progress: { id: 1, status: 'not_completed' },
      content_file: '',
      content_filename: '',
      content_html: '',
      content_type: 0,
      created_by: 'Cirrus Aircraft',
      desc: 'Perspective & Perspective+ Avionics Course',
      id: 401,
      jet_scoring: false,
      meta_tags: [],
      placeholder_image:
        'https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/content-files/5c480eb38443724475091bf0d91ba12.2.png',
      score: 0,
      show_comments: true,
      starter_file: '',
      subtitle: 'Hello Cockpit [2.1]',
      title: 'Hello Cockpit [2.1]',
      upload_image: '',
      url: '309005652',
    },

    content_id: 401,
    hidden: false,
    required: false,
    id: 1,
    title: '',
    updated_at: '',
    created_at: '',
  },
  instructor_intro_video: {
    content: {
      blob_directory: '',
      order: 0,
      quiz: '',
      content_tasks: [],
      progress: { id: 1, status: 'not_completed' },
      content_file: '',
      content_filename: '',
      content_html: '',
      content_type: 0,
      created_by: 'Cirrus Aircraft',
      desc: 'Perspective & Perspective+ Avionics Course',
      id: 401,
      jet_scoring: false,
      meta_tags: [],
      placeholder_image:
        'https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/content-files/5c480eb38443724475091bf0d91ba12.2.png',
      score: 0,
      show_comments: true,
      starter_file: '',
      subtitle: 'Hello Cockpit [2.1]',
      title: 'Hello Cockpit [2.1]',
      upload_image: '',
      url: '309005652',
    },
    content_id: 401,
    created_at: '2022-05-18T15:55:59.249Z',
    hidden: false,
    id: 69,
    required: false,
    title: 'hello',
    updated_at: '2022-05-18T15:55:59.249Z',
  },
  progress: {
    id: 0,
    status: 'not_started',
  },
  instructor_overview: '',
  instructor_contents: [],
  course_id: 0,
  course_attempt_id: 0,
  stage_id: 0,
  progress_stats: progressStats,
};

export const testData2: ILesson = {
  id: 832,
  system_desc:
    'The SR Series Systems self-study lesson for flight training courses.',
  updated_at: '2020-02-14T20:21:44.256Z',
  course_attempt_id: 0,
  course_id: 0,
  stage_id: 0,
  system_name: 'SR Series Systems Self Study Lesson - Flight Training Courses',
  lesson_type: 0,
  subtitle: '',
  thumbnail_image_url: '',
  mobile_hero_image_url: '',
  desktop_hero_image_url: '',
  title: 'Systems',
  overview:
    "<div><b>Self-Study Lesson</b></div><div>Estimated Lesson Time: 2.0 Hours</div><div><br></div><div>Learning about the aircraft's systems is fundamental to transitioning into your Cirrus. This lesson is designed to better connect you with your Cirrus by developing a comprehensive understanding, from the inside out.&nbsp;</div><div><br></div>",
  is_archived: false,
  contents_are_linear: false,
  is_preview: false,
  major_version: 1,
  minor_version: 2,
  contents: [
    {
      id: 630,
      title: 'Primary Flight Controls',
      subtitle: 'Primary Flight Controls',
      score: 0,
      url: '377578235',
      content_type: 0,
      meta_tags: [],
      content_tasks: [],
      content_html: '',
      desc: 'Primary Flight Controls video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a84173672f8f9d5c5aa4dd32e91068Primary Flight Controls.png',
      content_file: '',
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: '',
      content_filename: '',
      blob_directory: '',
      starter_file: '',
      show_comments: true,
      order: 0,
      quiz: 0,
      progress: {
        id: 0,
        status: 'not_started',
      },
    },
    {
      id: 631,
      title: 'Secondary Flight Controls ',
      subtitle: 'Secondary Flight Controls ',
      score: 0,
      url: '377578031',
      content_type: 0,
      meta_tags: [],
      content_tasks: [],
      content_html: '',
      desc: 'Secondary Flight Controls video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/3b7ad00c3fb97838bba10ac45f3d57Secondary Flight Controls.png',
      content_file: '',
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: '',
      content_filename: '',
      blob_directory: '',
      starter_file: '',
      show_comments: true,
      order: 1,
      quiz: 0,
      progress: {
        id: 0,
        status: 'not_started',
      },
    },
    {
      id: 632,
      title: 'Flight Controls & Trim: Controls, Operation, and Indications',
      subtitle: 'Flight Controls & Trim: Controls, Operation, and Indications',
      score: 0,
      url: '377578144',
      content_type: 0,
      meta_tags: [],
      content_tasks: [],
      content_html: '',
      desc: 'Flight Controls & Trim: Controls, Operation, and Indications video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/707a10514ac95bee353d6379d062dfControls, Operation, and Indications.png',
      content_file: '',
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: '',
      content_filename: '',
      blob_directory: '',
      starter_file: '',
      show_comments: true,
      order: 2,
      quiz: 0,
      progress: {
        id: 0,
        status: 'not_started',
      },
    },
  ],
  order: 0,
  overview_image_url: '',
  student_intro_video: {
    content: {
      blob_directory: '',
      order: 0,
      quiz: '',
      content_tasks: [],
      progress: { id: 1, status: 'not_completed' },
      content_file: '',
      content_filename: '',
      content_html: '',
      content_type: 0,
      created_by: 'Cirrus Aircraft',
      desc: 'Perspective & Perspective+ Avionics Course',
      id: 401,
      jet_scoring: false,
      meta_tags: [],
      placeholder_image:
        'https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/content-files/5c480eb38443724475091bf0d91ba12.2.png',
      score: 0,
      show_comments: true,
      starter_file: '',
      subtitle: 'Hello Cockpit [2.1]',
      title: 'Hello Cockpit [2.1]',
      upload_image: '',
      url: '309005652',
    },

    content_id: 401,
    hidden: false,
    required: false,
    id: 1,
    title: '',
    updated_at: '',
    created_at: '',
  },
  instructor_intro_video: {
    content: {
      blob_directory: '',
      order: 0,
      quiz: '',
      content_tasks: [],
      progress: { id: 1, status: 'not_completed' },
      content_file: '',
      content_filename: '',
      content_html: '',
      content_type: 0,
      created_by: 'Cirrus Aircraft',
      desc: 'Perspective & Perspective+ Avionics Course',
      id: 401,
      jet_scoring: false,
      meta_tags: [],
      placeholder_image:
        'https://cirrusapproachherokuprod.blob.core.windows.net/cirruslmsherokuprodcontainer/content-items/content-files/5c480eb38443724475091bf0d91ba12.2.png',
      score: 0,
      show_comments: true,
      starter_file: '',
      subtitle: 'Hello Cockpit [2.1]',
      title: 'Hello Cockpit [2.1]',
      upload_image: '',
      url: '309005652',
    },
    content_id: 401,
    created_at: '2022-05-18T15:55:59.249Z',
    hidden: false,
    id: 69,
    required: false,
    title: 'hello',
    updated_at: '2022-05-18T15:55:59.249Z',
  },
  progress: {
    id: 0,
    status: 'not_started',
  },
  instructor_overview: '',
  instructor_contents: [],
  progress_stats: progressStats,
};
