import { ILesson } from '@cirrus/models';

export const testData: ILesson = {
  id: 832,
  system_desc:
    'The SR Series Systems self-study lesson for flight training courses.',
  created_at: '2019-12-30T17:12:18.208Z',
  updated_at: '2020-02-14T20:21:44.256Z',
  system_name: 'SR Series Systems Self Study Lesson - Flight Training Courses',
  lesson_type: 0,
  title: 'Systems',
  overview:
    "<div><b>Self-Study Lesson</b></div><div>Estimated Lesson Time: 2.0 Hours</div><div><br></div><div>Learning about the aircraft's systems is fundamental to transitioning into your Cirrus. This lesson is designed to better connect you with your Cirrus by developing a comprehensive understanding, from the inside out.&nbsp;</div><div><br></div>",
  is_archived: null,
  contents_are_linear: false,
  is_preview: false,
  major_version: 1,
  minor_version: 2,
  contents: [
    {
      id: 630,
      title: 'Primary Flight Controls',
      subtitle: 'Primary Flight Controls',
      status: null,
      score: null,
      url: '377578235',
      estimated_time: '',
      created_at: '2019-12-05T20:12:31.880Z',
      updated_at: '2019-12-19T23:53:49.943Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Primary Flight Controls video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a84173672f8f9d5c5aa4dd32e91068Primary Flight Controls.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 0,
    },
    {
      id: 631,
      title: 'Secondary Flight Controls ',
      subtitle: 'Secondary Flight Controls ',
      status: null,
      score: null,
      url: '377578031',
      estimated_time: '',
      created_at: '2019-12-05T20:14:50.309Z',
      updated_at: '2019-12-19T23:53:25.678Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Secondary Flight Controls video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/3b7ad00c3fb97838bba10ac45f3d57Secondary Flight Controls.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 1,
    },
    {
      id: 632,
      title: 'Flight Controls & Trim: Controls, Operation, and Indications',
      subtitle: 'Flight Controls & Trim: Controls, Operation, and Indications',
      status: null,
      score: null,
      url: '377578144',
      estimated_time: '',
      created_at: '2019-12-05T20:17:57.087Z',
      updated_at: '2019-12-19T23:53:02.787Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Flight Controls & Trim: Controls, Operation, and Indications video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/707a10514ac95bee353d6379d062dfControls, Operation, and Indications.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 2,
    },
    {
      id: 633,
      title: 'Flight Controls & Trim: Abnormals',
      subtitle: 'Flight Controls & Trim: Abnormals',
      status: null,
      score: null,
      url: '377578202',
      estimated_time: '',
      created_at: '2019-12-05T20:36:36.018Z',
      updated_at: '2019-12-19T23:52:45.725Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Flight Controls & Trim: Abnormals video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a7eeb71cfbdf8c474ce3b31c226e3fAbnormals.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 3,
    },
    {
      id: 634,
      title: 'Flight Controls & Trim: Limitations ',
      subtitle: 'Flight Controls & Trim: Limitations ',
      status: null,
      score: null,
      url: '377563850',
      estimated_time: '',
      created_at: '2019-12-05T20:39:03.910Z',
      updated_at: '2020-01-03T18:07:52.717Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Flight Controls & Trim: Limitations video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/c85e6448368d091a47c5a2308249b7Limitations.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 4,
      show_comments: true,
      order: 4,
    },
    {
      id: 903,
      title: 'Flight Controls & Trim: Preflight',
      subtitle: 'Flight Controls & Trim: Preflight',
      status: null,
      score: null,
      url: '391547561',
      estimated_time: '',
      created_at: '2020-02-14T17:59:40.301Z',
      updated_at: '2020-02-14T20:09:53.392Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/c4b2d7e5d97c7a4651eea7aaa2dcf5Preflight.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 5,
    },
    {
      id: 893,
      title: 'Engine: Your Engine',
      subtitle: 'Engine: Your Engine',
      status: null,
      score: null,
      url: '389262073',
      estimated_time: '',
      created_at: '2020-02-10T18:29:56.786Z',
      updated_at: '2020-02-14T20:14:09.034Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Your Engine video SR2X systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/30a8d1c44cf9511b0505317ccc69853.1_Intro.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 5,
      show_comments: true,
      order: 6,
    },
    {
      id: 894,
      title: 'Engine: Reciprocating Engines',
      subtitle: 'Engine: Reciprocating Engines',
      status: null,
      score: null,
      url: '389262158',
      estimated_time: '',
      created_at: '2020-02-10T18:37:59.627Z',
      updated_at: '2020-02-10T18:39:41.616Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Reciprocating Engines video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/ca82e25d89f2e62fd0437a0a53f6413.2_Engine.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 7,
    },
    {
      id: 895,
      title: 'Engine: Induction System',
      subtitle: 'Engine: Induction System',
      status: null,
      score: null,
      url: '389262291',
      estimated_time: '',
      created_at: '2020-02-10T18:44:33.388Z',
      updated_at: '2020-02-10T18:44:47.447Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Induction System video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/f00e123b68d236f92cd1de2c047ebb3.3_InductionSystem.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 2,
      show_comments: true,
      order: 8,
    },
    {
      id: 896,
      title: 'Engine: Turbochargers',
      subtitle: 'Engine: Turbochargers',
      status: null,
      score: null,
      url: '389262412',
      estimated_time: '',
      created_at: '2020-02-10T18:46:16.736Z',
      updated_at: '2020-02-10T18:52:19.958Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Turbochargers video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/71ae998d234de932180d0c59555dba3.4_Turbochargers.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 2,
      show_comments: true,
      order: 9,
    },
    {
      id: 897,
      title: 'Engine: Ignition System',
      subtitle: 'Engine: Ignition System',
      status: null,
      score: null,
      url: '389262548',
      estimated_time: '',
      created_at: '2020-02-10T18:47:28.791Z',
      updated_at: '2020-02-10T18:47:28.791Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Ignition System video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/54324e34a2315add0e3e94191465bb3.5_Ignition.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 10,
    },
    {
      id: 898,
      title: 'Engine: Oil System',
      subtitle: 'Engine: Oil System',
      status: null,
      score: null,
      url: '389262638',
      estimated_time: '',
      created_at: '2020-02-10T18:52:05.601Z',
      updated_at: '2020-02-10T18:52:05.601Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Oil System video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/c3678db225375b5380fec2ec045a933.6_OilSystem.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 11,
    },
    {
      id: 899,
      title: 'Engine: Controls and Operation',
      subtitle: 'Engine: Controls and Operation',
      status: null,
      score: null,
      url: '389262693',
      estimated_time: '',
      created_at: '2020-02-10T18:53:34.323Z',
      updated_at: '2020-02-14T18:51:43.417Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Controls and Operations video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/7071bdf05ede5bca57c811132e1e873.7_Controls&Operations.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 2,
      show_comments: true,
      order: 12,
    },
    {
      id: 900,
      title: 'Engine: Indications and Limitations',
      subtitle: 'Engine: Indications and Limitations',
      status: null,
      score: null,
      url: '389262743',
      estimated_time: '',
      created_at: '2020-02-10T18:54:41.372Z',
      updated_at: '2020-02-10T18:54:41.372Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Indications and Limitations video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/589b58b344bb4347318c504c9728283.8_Indications&Limitations.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 13,
    },
    {
      id: 901,
      title: 'Engine: Abnormals',
      subtitle: 'Engine: Abnormals',
      status: null,
      score: null,
      url: '389262889',
      estimated_time: '',
      created_at: '2020-02-10T18:56:07.438Z',
      updated_at: '2020-02-10T18:56:07.438Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Abnormals video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/1d4bc6b7b2cd796b0d3c8df496e9903.9_Abnormals.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 14,
    },
    {
      id: 902,
      title: 'Engine: Abnormals SR22T',
      subtitle: 'Engine: Abnormals SR22T',
      status: null,
      score: null,
      url: '389263450',
      estimated_time: '',
      created_at: '2020-02-10T18:57:59.843Z',
      updated_at: '2020-02-10T18:57:59.843Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Engine: Abnormals SR22T video SR2X Systems Course',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/713105629e82b93d9f93d4acb83d773.10_Abnormals22T.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 15,
    },
    {
      id: 910,
      title: 'Engine: Preflight',
      subtitle: 'Engine: Preflight',
      status: null,
      score: null,
      url: '391570141',
      estimated_time: '',
      created_at: '2020-02-14T19:45:28.131Z',
      updated_at: '2020-02-14T19:45:28.131Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/1c668aa4746b0eccc83d556876701aPreflight.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 16,
    },
    {
      id: 907,
      title: 'Propeller: Components',
      subtitle: 'Propeller: Components',
      status: null,
      score: null,
      url: '391548079',
      estimated_time: '',
      created_at: '2020-02-14T18:49:23.133Z',
      updated_at: '2020-02-14T18:49:23.133Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/ae0a6cc58dbd043a3cc7fd084bf367Components.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 17,
    },
    {
      id: 906,
      title: 'Propeller: Controls & Operation',
      subtitle: 'Propeller: Controls & Operation',
      status: null,
      score: null,
      url: '391548084',
      estimated_time: '',
      created_at: '2020-02-14T18:47:54.991Z',
      updated_at: '2020-02-14T18:50:48.041Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/de35919541147739d7a6370a4d98dcControls.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 2,
      show_comments: true,
      order: 18,
    },
    {
      id: 905,
      title: 'Propeller: Abnormals',
      subtitle: 'Propeller: Abnormals',
      status: null,
      score: null,
      url: '391548093',
      estimated_time: '',
      created_at: '2020-02-14T18:45:47.311Z',
      updated_at: '2020-02-14T18:45:47.311Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/08ec905c0b2dad4d97df02912193f7Abnormals.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 19,
    },
    {
      id: 904,
      title: 'Propeller: Preflight',
      subtitle: 'Propeller: Preflight',
      status: null,
      score: null,
      url: '391548103',
      estimated_time: '',
      created_at: '2020-02-14T18:01:20.047Z',
      updated_at: '2020-02-14T18:36:24.332Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/40c594d2ae1a5983eb925d21a96723Preflight.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 2,
      show_comments: true,
      order: 20,
    },
    {
      id: 635,
      title: 'Landing Gear, Hydraulics, & Brakes: Components',
      subtitle: 'Landing Gear, Hydraulics, & Brakes: Components',
      status: null,
      score: null,
      url: '377573879',
      estimated_time: '',
      created_at: '2019-12-05T20:42:43.086Z',
      updated_at: '2019-12-19T23:51:41.271Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Landing Gear, Hydraulics, & Brakes: Components video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/2a0ff382eb1d1b4cc3bef036072837Components.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 21,
    },
    {
      id: 636,
      title: 'Landing Gear, Hydraulics, & Brakes: Controls & Operation',
      subtitle: 'Landing Gear, Hydraulics, & Brakes: Controls & Operation',
      status: null,
      score: null,
      url: '377573772',
      estimated_time: '',
      created_at: '2019-12-05T20:44:25.316Z',
      updated_at: '2019-12-19T23:51:00.609Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Landing Gear, Hydraulics, & Brakes: Controls & Operation video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/41dd365a103135d98e9a60e29d1317Controls and Operations.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 22,
    },
    {
      id: 637,
      title: 'Landing Gear, Hydraulics, & Brakes: Abnormals',
      subtitle: 'Landing Gear, Hydraulics, & Brakes: Abnormals',
      status: null,
      score: null,
      url: '377573836',
      estimated_time: '',
      created_at: '2019-12-05T20:45:55.849Z',
      updated_at: '2019-12-19T23:50:38.438Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Landing Gear, Hydraulics, & Brakes: Abnormals video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/236f9a960fc9b985f1f9fcf23ac32dAbnormals (1).png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 23,
    },
    {
      id: 909,
      title: 'Landing Gear, Hydraulics, and Brakes: Preflight',
      subtitle: 'Landing Gear, Hydraulics, and Brakes: Preflight',
      status: null,
      score: null,
      url: '391566371',
      estimated_time: '',
      created_at: '2020-02-14T19:27:13.393Z',
      updated_at: '2020-02-14T19:27:13.393Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/d1ddaa4363308289799948776dac72Preflight.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 1,
      show_comments: true,
      order: 24,
    },
    {
      id: 650,
      title: 'Environmental System: Components',
      subtitle: 'Environmental System: Components',
      status: null,
      score: null,
      url: '333114222',
      estimated_time: '',
      created_at: '2019-12-10T21:01:45.553Z',
      updated_at: '2019-12-19T23:35:33.649Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Environmental System: Components video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/50ce5b183e58079cc3614173aa2e2a10.1.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 25,
    },
    {
      id: 651,
      title: 'Environmental System: Air Conditioning',
      subtitle: 'Environmental System: Air Conditioning',
      status: null,
      score: null,
      url: '333114996',
      estimated_time: '',
      created_at: '2019-12-10T21:04:37.745Z',
      updated_at: '2019-12-19T23:35:59.416Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Environmental System: Air Conditioning video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/f08fb2828a3732e511a9cf72f9b5e010.2.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 26,
    },
    {
      id: 652,
      title: 'Environmental System: Controls, Operation, and Limitations',
      subtitle: 'Environmental System: Controls, Operation, and Limitations',
      status: null,
      score: null,
      url: '333115865',
      estimated_time: '',
      created_at: '2019-12-10T21:06:31.205Z',
      updated_at: '2019-12-19T23:35:14.744Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Environmental System: Controls, Operation, and Limitations video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/c7ce427f1d9ef1eddd6a24d85dd5e610.3.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 27,
    },
    {
      id: 653,
      title: 'Environmental System: Abnormals',
      subtitle: 'Environmental System: Abnormals',
      status: null,
      score: null,
      url: '333116644',
      estimated_time: '',
      created_at: '2019-12-10T21:07:39.230Z',
      updated_at: '2019-12-19T23:34:56.083Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Environmental System: Abnormals video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a49c4a42961ce913be636b8f47df3a10.4.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 28,
    },
    {
      id: 638,
      title: 'Fuel System: Components',
      subtitle: 'Fuel System: Components',
      status: null,
      score: null,
      url: '330834720',
      estimated_time: '',
      created_at: '2019-12-10T15:32:16.266Z',
      updated_at: '2019-12-19T23:50:17.501Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Fuel System: Components video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/f6141b181ff38611b0b36614c2ee688.1.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 29,
    },
    {
      id: 640,
      title: 'Fuel System: Controls & Operation',
      subtitle: 'Fuel System: Controls & Operation',
      status: null,
      score: null,
      url: '330837024',
      estimated_time: '',
      created_at: '2019-12-10T15:35:37.913Z',
      updated_at: '2019-12-19T23:49:29.538Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Fuel System: Controls & Operation video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/b8098bcf09ae308f8b466d0c9e696d8.3..png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 30,
    },
    {
      id: 639,
      title: 'Fuel System: Indications',
      subtitle: 'Fuel System: Indications',
      status: null,
      score: null,
      url: '330841543',
      estimated_time: '',
      created_at: '2019-12-10T15:33:57.268Z',
      updated_at: '2019-12-19T23:49:55.463Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Fuel System: Indications video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/eb6162f198dc53460934ce571c23bc8.2.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 31,
    },
    {
      id: 641,
      title: 'Fuel System: Abnormals',
      subtitle: 'Fuel System: Abnormals',
      status: null,
      score: null,
      url: '333590374',
      estimated_time: '',
      created_at: '2019-12-10T15:37:27.682Z',
      updated_at: '2019-12-19T23:49:04.945Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Fuel System: Abnormals video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/2c8bb1f3a40b528b79a7c3e823bbfa8.4.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 32,
    },
    {
      id: 642,
      title: 'Fuel System: Limitations',
      subtitle: 'Fuel System: Limitations',
      status: null,
      score: null,
      url: '330843980',
      estimated_time: '',
      created_at: '2019-12-10T15:43:19.656Z',
      updated_at: '2019-12-19T23:42:26.565Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Fuel System: Components video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a0aab5ad0131ad9302e1ffcb1e19bd8.5.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 33,
    },
    {
      id: 908,
      title: 'Fuel System: Preflight',
      subtitle: 'Fuel System: Preflight',
      status: null,
      score: null,
      url: '391560344',
      estimated_time: '',
      created_at: '2020-02-14T18:58:47.695Z',
      updated_at: '2020-02-14T19:28:42.171Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: '',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/content-files/b3dc8953354617f411e78ee48cbbb3Preflight.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 2,
      show_comments: true,
      order: 34,
    },
    {
      id: 649,
      title: 'Electrical System: Components & Limitations',
      subtitle: 'Electrical System: Components & Limitations',
      status: null,
      score: null,
      url: '367009908',
      estimated_time: '',
      created_at: '2019-12-10T20:56:04.181Z',
      updated_at: '2019-12-19T23:39:11.378Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Electrical System: Components & Limitations video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/e99c29b486324a9e92e258b9f1dec19.1Components and Limitations.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 6,
      show_comments: true,
      order: 35,
    },
    {
      id: 645,
      title: ' Electrical System: Distribution',
      subtitle: ' Electrical System: Distribution',
      status: null,
      score: null,
      url: '367012568',
      estimated_time: '',
      created_at: '2019-12-10T20:50:12.382Z',
      updated_at: '2019-12-19T23:40:27.532Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Electrical System: Distribution video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/234a39cf49b297623aa8f6b98f64689.3_Distribution.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 5,
      show_comments: true,
      order: 36,
    },
    {
      id: 644,
      title: 'Electrical System: Controls & Operation',
      subtitle: 'Electrical System: Controls & Operation',
      status: null,
      score: null,
      url: '367011795',
      estimated_time: '',
      created_at: '2019-12-10T20:47:04.912Z',
      updated_at: '2019-12-19T23:38:04.599Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Environmental System: Controls & Operation video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/08a95b83bcf311cff82422d00d65ef9.2_Controls and Operation.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 37,
    },
    {
      id: 646,
      title: 'Electrical System: Indications',
      subtitle: 'Electrical System: Indications',
      status: null,
      score: null,
      url: '367014122',
      estimated_time: '',
      created_at: '2019-12-10T20:51:46.469Z',
      updated_at: '2019-12-19T23:40:13.972Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Electrical System: Indications video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/932f65f2cf7cc017c6f4aac47257b69.4_Indications.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 5,
      show_comments: true,
      order: 38,
    },
    {
      id: 647,
      title: 'Electrical System: Abnormals',
      subtitle: 'Electrical System: Abnormals',
      status: null,
      score: null,
      url: '367014807',
      estimated_time: '',
      created_at: '2019-12-10T20:53:19.216Z',
      updated_at: '2019-12-19T23:39:58.700Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Electrical System: Abnormals video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/c05c1ce576e66b789796c292ddfa4c9.5_Abnormals.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 5,
      show_comments: true,
      order: 39,
    },
    {
      id: 648,
      title: ' Electrical System: Preflight',
      subtitle: ' Electrical System: Preflight',
      status: null,
      score: null,
      url: '367017213',
      estimated_time: '',
      created_at: '2019-12-10T20:55:26.441Z',
      updated_at: '2019-12-19T23:39:46.723Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Electrical System: Preflight video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a62b4a8d205bfb8cd6826a2c18b65e9.6_Preflight.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus AIrcraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 5,
      show_comments: true,
      order: 40,
    },
    {
      id: 654,
      title: 'Oxygen System: Components',
      subtitle: 'Oxygen System: Components',
      status: null,
      score: null,
      url: '361832311',
      estimated_time: '',
      created_at: '2019-12-10T21:11:45.573Z',
      updated_at: '2019-12-19T23:34:32.058Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Oxygen System: Components video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/41e08c1314a675721f9663aae1c17812.1_Components.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 41,
    },
    {
      id: 657,
      title: 'Oxygen System: Controls, Operation, & Indications',
      subtitle: 'Oxygen System: Controls, Operation, & Indications',
      status: null,
      score: null,
      url: '361833777',
      estimated_time: '',
      created_at: '2019-12-10T21:16:57.920Z',
      updated_at: '2019-12-20T00:37:53.351Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Oxygen System: Controls, Operation, & Indications video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/28fc5cb91f37c166a532044a00736812.2_Controls Operation and Indications.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 6,
      show_comments: true,
      order: 42,
    },
    {
      id: 656,
      title: 'Oxygen System: Abnormals',
      subtitle: 'Oxygen System: Abnormals',
      status: null,
      score: null,
      url: '361835999',
      estimated_time: '',
      created_at: '2019-12-10T21:16:19.430Z',
      updated_at: '2019-12-19T23:32:42.539Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Oxygen System: Abnormals video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/53d796fb1f09703d9a3f8715914e5a12.3_Abnormals.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 43,
    },
    {
      id: 658,
      title: 'Oxygen System: Limitations & Regulations',
      subtitle: 'Oxygen System: Limitations & Regulations',
      status: null,
      score: null,
      url: '361837672',
      estimated_time: '',
      created_at: '2019-12-10T21:21:17.020Z',
      updated_at: '2019-12-19T23:31:14.137Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Oxygen System: Limitations & Regulations video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/8af54a7527d7e5215bad7ddc84aad612.4_Limitations and Regulations.png',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 44,
    },
    {
      id: 659,
      title: 'Oxygen System: Preflight',
      subtitle: 'Oxygen System: Preflight',
      status: null,
      score: null,
      url: '361863676',
      estimated_time: '',
      created_at: '2019-12-10T21:22:43.164Z',
      updated_at: '2019-12-19T23:30:51.816Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Oxygen System: Preflight video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/08e181562633cee26c52731d9a336d12.5_Preflight.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 45,
    },
    {
      id: 660,
      title: 'Oxygen System: Portable Systems',
      subtitle: 'Oxygen System: Portable Systems',
      status: null,
      score: null,
      url: '361864863',
      estimated_time: '',
      created_at: '2019-12-10T21:24:10.754Z',
      updated_at: '2019-12-19T23:30:32.824Z',
      content_type: 0,
      meta_tags: [],
      content_html: null,
      link_id: null,
      desc: 'Oxygen System: Portable Systems video from the SR2X systems video series.',
      placeholder_image:
        'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/d0cca0e9626757f8de73d42ea0a27512.6Portable Systems.jpg',
      content_file: null,
      jet_scoring: false,
      created_by: 'Cirrus Aircraft',
      upload_image: null,
      content_filename: '',
      blob_directory: null,
      starter_file: null,
      version: 3,
      show_comments: true,
      order: 46,
    },
  ],
};
