import { ILesson, ProgressType } from '@cirrus/models';

export const testData: { lesson: ILesson } = {
  lesson: {
    id: 832,
    subTitle: 'SR Series Systems Self Study Lesson - Flight Training Courses',
    progess: [
      {
        type: ProgressType.Ground,
        completedCourses: 5,
        totalCourses: 10,
      },
      {
        type: ProgressType.Flight,
        completedCourses: 12,
        totalCourses: 20,
      },
      {
        type: ProgressType.Land,
        completedCourses: 10,
        totalCourses: 14,
      },
      {
        type: ProgressType.Land,
        completedCourses: 9,
        totalCourses: 12,
      },
      {
        type: ProgressType.Land,
        completedCourses: 12,
        totalCourses: 20,
      },
    ],
    system_desc:
      'The SR Series Systems self-study lesson for flight training courses.',
    created_at: '2019-12-30T17:12:18.208Z',
    updated_at: '2020-02-14T20:21:44.256Z',
    system_name:
      'SR Series Systems Self Study Lesson - Flight Training Courses',
    lesson_type: 0,
    title: 'Systems',
    overview:
      "<div><b>Self-Study Lesson</b></div><div>Estimated Lesson Time: 2.0 Hours</div><div><br></div><div>Learning about the aircraft's systems is fundamental to transitioning into your Cirrus. This lesson is designed to better connect you with your Cirrus by developing a comprehensive understanding, from the inside out.&nbsp;</div><div><br></div>",
    is_archived: null,
    contents_are_linear: false,
    is_preview: false,
    major_version: 1,
    minor_version: 2,
    contents: [
      {
        id: 630,
        title: 'Primary Flight Controls',
        subtitle: 'Primary Flight Controls',
        status: null,
        score: null,
        url: '377578235',
        created_at: '2019-12-05T20:12:31.880Z',
        updated_at: '2019-12-19T23:53:49.943Z',
        content_type: 0,
        meta_tags: [],
        content_html: null,
        link_id: null,
        desc: 'Primary Flight Controls video from the SR2X systems video series.',
        placeholder_image:
          'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/a84173672f8f9d5c5aa4dd32e91068Primary Flight Controls.png',
        content_file: null,
        jet_scoring: false,
        created_by: 'Cirrus Aircraft',
        upload_image: null,
        content_filename: '',
        blob_directory: null,
        starter_file: null,
        version: 3,
        show_comments: true,
        order: 0,
      },
      {
        id: 631,
        title: 'Secondary Flight Controls ',
        subtitle: 'Secondary Flight Controls ',
        status: null,
        score: null,
        url: '377578031',
        created_at: '2019-12-05T20:14:50.309Z',
        updated_at: '2019-12-19T23:53:25.678Z',
        content_type: 0,
        meta_tags: [],
        content_html: null,
        link_id: null,
        desc: 'Secondary Flight Controls video from the SR2X systems video series.',
        placeholder_image:
          'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/3b7ad00c3fb97838bba10ac45f3d57Secondary Flight Controls.png',
        content_file: null,
        jet_scoring: false,
        created_by: 'Cirrus Aircraft',
        upload_image: null,
        content_filename: '',
        blob_directory: null,
        starter_file: null,
        version: 3,
        show_comments: true,
        order: 1,
      },
      {
        id: 632,
        title: 'Flight Controls & Trim: Controls, Operation, and Indications',
        subtitle:
          'Flight Controls & Trim: Controls, Operation, and Indications',
        status: null,
        score: null,
        url: '377578144',
        created_at: '2019-12-05T20:17:57.087Z',
        updated_at: '2019-12-19T23:53:02.787Z',
        content_type: 0,
        meta_tags: [],
        content_html: null,
        link_id: null,
        desc: 'Flight Controls & Trim: Controls, Operation, and Indications video from the SR2X systems video series.',
        placeholder_image:
          'https://content.cirrusapproach.com/cirruslmsherokuprodcontainer/content-items/scorm/707a10514ac95bee353d6379d062dfControls, Operation, and Indications.png',
        content_file: null,
        jet_scoring: false,
        created_by: 'Cirrus Aircraft',
        upload_image: null,
        content_filename: '',
        blob_directory: null,
        starter_file: null,
        version: 3,
        show_comments: true,
        order: 2,
      },
    ],
  },
};
