import { ICourseOverview, PROGRESS_STATUS } from '@cirrus/models';

export const course466: ICourseOverview = {
  id: 466,
  name: 'SR Series Takeoffs and Landings Course',
  overview:
    'Every adventure begins with a takeoff and concludes with a landing - the SR Series Takeoffs and Landings course takes an in-depth look at these everyday procedures to make every takeoff and landing safe, predictable, and repeatable. This course takes a straight-forward practical approach towards each aspect of your takeoff and landing, leaving no detail behind. It puts you behind the controls with fun and instructive 3D graphics, first-person demonstrations by a Cirrus Standardized Instructor Pilot, and the ability to complete each lesson at your own pace.\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cb\u003eCourse Time:\u003c/b\u003e\u0026nbsp;5.5 hours (estimate)\u003cbr\u003e\u003c/div\u003e',
  major_version: 1,
  minor_version: 2,
  title: 'SR Series Takeoffs and Landings Course',
  subtitle: '',
  has_agreement: false,
  agreement_body: '',
  completion_time: '1h 1m',
  minimum_flight_hours: 0,
  desktop_hero_image_url: '',
  mobile_hero_image_url: '',
  thumbnail_image_url: '',
  can_reenroll: true,
  lessons_stats: { completed: 0, total: 12 },
  summary_counts: { lessons: 12, videos: 50 },
  certificate: { expiration: null },
  course_content_stats: [
    { type: 'self_study', completed: 0, total: 51 },
    { type: 'flight_assessment', completed: 0, total: 0 },
    { type: 'ground_assessment', completed: 0, total: 0 },
  ],
  hours_and_landings_stats: [
    { type: 'completed_total_hours', completed: 0.0 },
    { type: 'completed_ground_instruction_hours', completed: 0.0 },
    { type: 'completed_sim_hours', completed: 0.0 },
    { type: 'completed_cross_country_hours', completed: 0.0 },
    { type: 'completed_total_landings', completed: 0.0 },
  ],
  stages: [
    {
      id: 495,
      title: 'Course Intro',
      desc: '',
      overview: '',
      order: 0,
      lessons_are_linear: false,
      lessons: [
        {
          id: 856,
          stage_id: 495,
          title: 'Your Cirrus Training Edited',
          subtitle: '',
          order: 0,
          index: '1.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '1h 1m',
          content_counts: {},
          progress: { id: 0, status: 'not_started' },
        },
      ],
      progress: { id: 1776118, status: 'not_started' },
    },
    {
      id: 484,
      title: 'SR Series Takeoffs and Landings',
      desc: '',
      overview: '',
      order: 1,
      lessons_are_linear: false,
      lessons: [
        {
          id: 1002,
          stage_id: 484,
          title: 'Intro',
          subtitle: '',
          order: 0,
          index: '2.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 1 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1003,
          stage_id: 484,
          title: 'Essential Elements',
          subtitle: '',
          order: 1,
          index: '2.2',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 12 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1004,
          stage_id: 484,
          title: 'Traffic Pattern ',
          subtitle: '',
          order: 2,
          index: '2.3',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1005,
          stage_id: 484,
          title: 'Stabilized Approach',
          subtitle: '',
          order: 3,
          index: '2.4',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 5 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1049,
          stage_id: 484,
          title: 'Faulty Approach',
          subtitle: '',
          order: 4,
          index: '2.5',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1006,
          stage_id: 484,
          title: 'Normal Takeoff and Landing',
          subtitle: '',
          order: 5,
          index: '2.6',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1007,
          stage_id: 484,
          title: 'Crosswinds and Slips',
          subtitle: '',
          order: 6,
          index: '2.7',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1008,
          stage_id: 484,
          title: 'Short-Field Takeoff and Landing',
          subtitle: '',
          order: 7,
          index: '2.8',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 5 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1009,
          stage_id: 484,
          title: 'Soft/Rough-Field Takeoff and Landing',
          subtitle: '',
          order: 8,
          index: '2.9',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1050,
          stage_id: 484,
          title: 'Abnormal/Emergency',
          subtitle: '',
          order: 9,
          index: '2.10',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1051,
          stage_id: 484,
          title: 'Night Operations',
          subtitle: '',
          order: 10,
          index: '2.11',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 3 },
          progress: { id: -1, status: 'not_started' },
        },
      ],
      progress: { id: 1776121, status: 'not_started' },
    },
  ],
  progress: { id: -1, status: 'not_started' },
  enrollments: [
    {
      id: 119073,
      course_version: '1.10',
      enrollment_date: '09/15/22 - present',
      transcript_available: false,
      progress: { id: 1776117, status: PROGRESS_STATUS.in_progress },
      user_certificate: null,
    },
  ],
  next_lesson: {
    id: 856,
    stage_id: 495,
    title: 'Your Cirrus Training Edited',
    subtitle: '',
    order: 0,
    index: '1.1',
    thumbnail_image_url: '',
    lesson_type: 0,
    completion_time: '',
    content_counts: {},
    progress: { id: -1, status: 'not_started' },
  },
};

export const blankCourse: ICourseOverview = {
  id: 0,
  name: 'name',
  major_version: 0,
  minor_version: 0,
  title: 'title',
  subtitle: 'subtitle',
  has_agreement: true,
  certificate: {
    expiration: null,
  },
  course_content_stats: [],
  agreement_body: '',
  overview: '',
  completion_time: '',
  minimum_flight_hours: 0,
  desktop_hero_image_url: '',
  mobile_hero_image_url: '',
  thumbnail_image_url: '',
  can_reenroll: false,
  hours_and_landings_stats: [],
  lessons_stats: {
    completed: 0,
    total: 0,
  },
  summary_counts: {},
  stages: [],
  progress: { id: 0, status: PROGRESS_STATUS.not_started },
  enrollments: [],
  next_lesson: {},
};
