import {
  HoursAndLandingStatType,
  ICourseOverview,
  PROGRESS_STATUS,
} from '@cirrus/models';

export const course351: ICourseOverview = {
  badge: {
    id: 0,
    name: '',
    desc: '',
    badge_image: '',
    progress: 0,
    isActive: false,
  },
  started_at: '',
  id: 351,
  name: 'SR20 Avidyne Entegra Advanced Transition ',
  major_version: 4,
  minor_version: 11,
  title: 'SR20 Avidyne Entegra Advanced Transition ',
  subtitle: '',
  has_agreement: true,
  hours_and_landings_stats: [
    { type: HoursAndLandingStatType.completed_total_hours, completed: 0 },
    {
      type: HoursAndLandingStatType.completed_ground_instruction_hours,
      completed: 0,
    },
    { type: HoursAndLandingStatType.completed_sim_hours, completed: 0 },
    {
      type: HoursAndLandingStatType.completed_cross_country_hours,
      completed: 0,
    },
    { type: HoursAndLandingStatType.completed_total_landings, completed: 0 },
  ],
  certificate: {
    expiration: null,
  },
  completed_at: '',
  course_attempt: { id: 0 },
  thumbnail_image_url: '',
  course_content_stats: [
    {
      type: 'self_study',
      completed: 13,
      total: 73,
    },
    {
      type: 'flight_assessment',
      completed: 1,
      total: 9,
    },
    {
      type: 'ground_assessment',
      completed: 1,
      total: 1,
    },
  ],
  agreement_body:
    '\u003cp class="MsoNormal"\u003eThis training is limited to aircraft familiarization training and is not inclusive of all the knowledge and skill required for safe flight. I must comply with the regulations, exercise sound judgment, and maintain a high level of flying proficiency to minimize the risks associated with flight.\u0026nbsp;\u003c/p\u003e\u003cp class="MsoNormal"\u003e\u003cbr\u003e\u003c/p\u003e\u003cp class="MsoNormal"\u003eSafely flying under Instrument Flight Rules (IFR) requires peak levels of skill, sound decision making, and good risk management skills. Many IFR skills degrade over periods of inactivity and each pilot must assess risks for individual flights considering their proficiency levels required to handle forecasted weather, airspace, and other challenges that may arise. Pilots who desire to fly IFR are strongly encouraged to complete an Instrument Proficiency Check in 6-month intervals, regardless of IFR currency requirements.\u0026nbsp;\u0026nbsp;\u003c/p\u003e\u003cp class="MsoNormal"\u003e\u003cbr\u003e\u003c/p\u003e\u003cp class="MsoNormal"\u003eI acknowledge that for my continued proficiency and safety, Cirrus Aircraft strongly recommends that all pilots conduct recurrent training from an approved Cirrus Standardized Instructor Pilot (CSIP) or Cirrus Training Center (CTC).\u003c/p\u003e\u003cp class="MsoNormal"\u003e\u003cbr\u003e\u003c/p\u003e\u003cp class="MsoNormal"\u003eI acknowledge that my instructor will only observe my flight proficiency during this training for the task prescribed in this course. These tasks may not be inclusive of all the knowledge and skill required to safely fly under visual or instrument flight rules.\u003c/p\u003e',
  completion_time: '',
  minimum_flight_hours: 0,
  desktop_hero_image_url: '',
  mobile_hero_image_url: '',
  can_reenroll: true,
  lessons_stats: {
    completed: 2,
    total: 15,
  },
  summary_counts: {
    lessons: 15,
    videos: 65,
    documents: 7,
    assessments: 10,
  },
  stages: [
    {
      id: 243,
      title: 'Course Intro',
      desc: '',
      overview: '',
      order: 0,
      lessons_are_linear: false,
      lessons: [
        {
          id: 692,
          title: 'Welcome To Your Cirrus Training',
          subtitle: '',
          order: 0,
          index: '1.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            documents: 3,
          },
          progress: {
            id: 1775463,
            status: 'completed',
          },
          stage_id: 243,
        },
      ],
      progress: {
        id: 1775462,
        status: 'completed',
      },
    },
    {
      id: 244,
      title: 'Self Study',
      desc: '',
      overview: '',
      order: 1,
      lessons_are_linear: false,
      lessons: [
        {
          id: 857,
          title: 'CAPS',
          subtitle: '',
          order: 0,
          index: '2.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 10,
          },
          progress: {
            id: 1775468,
            status: 'completed',
          },
          stage_id: 244,
        },
        {
          id: 318,
          title: 'Takeoffs and Landings',
          subtitle: '',
          order: 1,
          index: '2.2',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 49,
          },
          progress: {
            id: 1775479,
            status: 'not_started',
          },
          stage_id: 244,
        },
        {
          id: 317,
          title: 'Engine Management',
          subtitle: '',
          order: 2,
          index: '2.3',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 6,
          },
          progress: {
            id: 1775529,
            status: 'not_started',
          },
          stage_id: 244,
        },
        {
          id: 595,
          title: 'Workbook',
          subtitle: '',
          order: 3,
          index: '2.4',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            documents: 3,
          },
          progress: {
            id: 1775536,
            status: 'not_started',
          },
          stage_id: 244,
        },
      ],
      progress: {
        id: 1775467,
        status: 'in_progress',
      },
    },
    {
      id: 245,
      title: 'Transition',
      desc: '',
      overview: '',
      order: 2,
      lessons_are_linear: false,
      lessons: [
        {
          id: 834,
          title: 'Lesson 1',
          subtitle: '',
          order: 0,
          index: '3.1',
          thumbnail_image_url: '',
          lesson_type: 1,
          completion_time: '',
          content_counts: {
            documents: 1,
            assessments: 1,
          },
          progress: {
            id: 1775541,
            status: 'not_started',
          },
          stage_id: 245,
        },
        {
          id: 835,
          title: 'Lesson 2',
          subtitle: '',
          order: 1,
          index: '3.2',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775545,
            status: 'not_started',
          },
          stage_id: 245,
        },
        {
          id: 836,
          title: 'Lesson 3',
          subtitle: '',
          order: 2,
          index: '3.3',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775547,
            status: 'not_started',
          },
          stage_id: 245,
        },
        {
          id: 837,
          title: 'Lesson 4',
          subtitle: '',
          order: 3,
          index: '3.4',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775549,
            status: 'not_started',
          },
          stage_id: 245,
        },
        {
          id: 838,
          title: 'Lesson 5',
          subtitle: '',
          order: 4,
          index: '3.5',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775551,
            status: 'not_started',
          },
          stage_id: 245,
        },
        {
          id: 839,
          title: 'Lesson 6',
          subtitle: '',
          order: 5,
          index: '3.6',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775553,
            status: 'not_started',
          },
          stage_id: 245,
        },
      ],
      progress: {
        id: 1775540,
        status: 'not_started',
      },
    },
    {
      id: 246,
      title: 'Advanced',
      desc: '',
      overview: '',
      order: 3,
      lessons_are_linear: false,
      lessons: [
        {
          id: 840,
          title: 'Lesson 7',
          subtitle: '',
          order: 0,
          index: '4.1',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775556,
            status: 'not_started',
          },
          stage_id: 246,
        },
        {
          id: 841,
          title: 'Lesson 8',
          subtitle: '',
          order: 1,
          index: '4.2',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775558,
            status: 'not_started',
          },
          stage_id: 246,
        },
        {
          id: 842,
          title: 'Lesson 9',
          subtitle: '',
          order: 2,
          index: '4.3',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775560,
            status: 'not_started',
          },
          stage_id: 246,
        },
        {
          id: 843,
          title: 'Lesson 10',
          subtitle: '',
          order: 3,
          index: '4.4',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '',
          content_counts: {
            assessments: 1,
          },
          progress: {
            id: 1775562,
            status: 'not_started',
          },
          stage_id: 246,
        },
      ],
      progress: {
        id: 1775555,
        status: 'not_started',
      },
    },
  ],
  progress: {
    id: 1775461,
    status: 'in_progress',
  },
  enrollments: [
    {
      id: 119061,
      course_version: '1.14',
      enrollment_date: '06/10/22 - present',
      transcript_available: false,
      progress: {
        id: 1775461,
        status: PROGRESS_STATUS.in_progress,
      },
      user_certificate: { id: 0, expires_on: '' },
    },
  ],
  next_lesson: {
    id: 692,
    title: 'Welcome To Your Cirrus Training',
    subtitle: '',
    order: 0,
    index: '1.1',
    thumbnail_image_url: '',
    lesson_type: 0,
    completion_time: '',
    content_counts: {
      documents: 3,
    },
  },
};

export const course357: ICourseOverview = {
  badge: {
    id: 0,
    name: '',
    desc: '',
    badge_image: '',
    progress: 0,
    isActive: false,
  },
  started_at: '',
  id: 357,
  name: 'Avidyne Entegra Advanced Avionics Differences',
  overview:
    '\u003cdiv\u003e\u003cspan style="background-color: transparent; font-size: 0.875rem;"\u003eThis avionics familiarity course is designed for instrument-rated pilots who want to explore the capabilities of the Avidyne Entegra avionics system. It\'s a proven syllabus to help transition experienced Cirrus pilots to cockpits equipped with\u0026nbsp;\u003c/span\u003eAvidyne Entegra\u003cspan style="background-color: transparent; font-size: 0.875rem;"\u003e\u0026nbsp;avionics.\u0026nbsp;\u003c/span\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cb style="background-color: transparent; font-size: 0.875rem;"\u003e\u003cbr\u003e\u003c/b\u003e\u003c/div\u003e\u003cdiv\u003e\u003cb style="background-color: transparent; font-size: 0.875rem;"\u003eFlight Time:\u0026nbsp;\u003c/b\u003e\u003cspan style="background-color: transparent; font-size: 0.875rem;"\u003e10 Hours (estimate)\u003c/span\u003e\u003cbr\u003e\u003c/div\u003e',
  major_version: 2,
  minor_version: 14,
  title: 'Avidyne Entegra Advanced Avionics Differences',
  subtitle: '',
  has_agreement: true,
  agreement_body:
    '\u003cdiv\u003eThis training is limited to aircraft familiarization training and is not inclusive of all the knowledge and skill required for safe flight. I must comply with the regulations, exercise sound judgment, and maintain a high level of flying proficiency to minimize the risks associated with flight.\u0026nbsp;\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003eSafely flying under Instrument Flight Rules (IFR) requires peak levels of skill, sound decision making, and good risk management skills. Many IFR skills degrade over periods of inactivity and each pilot must assess risks for individual flights considering their proficiency levels required to handle forecasted weather, airspace, and other challenges that may arise. Pilots who desire to fly IFR are strongly encouraged to complete an Instrument Proficiency Check in 6-month intervals, regardless of IFR currency requirements.\u0026nbsp;\u0026nbsp;\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003eI acknowledge that for my continued proficiency and safety, Cirrus Aircraft strongly recommends that all pilots conduct recurrent training from an approved Cirrus Standardized Instructor Pilot (CSIP) or Cirrus Training Center (CTC).\u003c/div\u003e\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003eI acknowledge that my instructor will only observe my flight proficiency during this training for the task prescribed in this course. These tasks may not be inclusive of all the knowledge and skill required to safely fly under visual or instrument flight rules.\u003c/div\u003e',
  completion_time: '',
  minimum_flight_hours: 0,
  desktop_hero_image_url: '',
  thumbnail_image_url: '',
  mobile_hero_image_url: '',
  can_reenroll: true,
  lessons_stats: { completed: 1, total: 7 },
  summary_counts: { lessons: 7, documents: 3, assessments: 6 },
  certificate: { expiration: null },
  completed_at: '',
  course_attempt: { id: 0 },
  course_content_stats: [
    { type: 'self_study', completed: 3, total: 3 },
    { type: 'flight_assessment', completed: 0, total: 6 },
    { type: 'ground_assessment', completed: 0, total: 0 },
  ],
  hours_and_landings_stats: [
    { type: 'completed_total_hours', completed: 0.0 },
    { type: 'completed_ground_instruction_hours', completed: 1.0 },
    { type: 'completed_sim_hours', completed: 1.0 },
    { type: 'completed_cross_country_hours', completed: 1.0 },
    { type: 'completed_total_landings', completed: 0.0 },
  ],
  stages: [
    {
      id: 261,
      title: 'Course Intro',
      desc: '',
      overview: '',
      order: 0,
      lessons_are_linear: false,
      lessons: [
        {
          id: 645,
          stage_id: 261,
          title: 'Your Cirrus Training',
          subtitle: '',
          order: 0,
          index: '1.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '1h 1m',
          content_counts: { documents: 3 },
          progress: { id: 1775577, status: 'completed' },
        },
      ],
      progress: { id: 1775576, status: 'completed' },
    },
    {
      id: 262,
      title: 'Instructor-Led Training',
      desc: '',
      overview: '',
      order: 1,
      lessons_are_linear: false,
      lessons: [
        {
          id: 846,
          stage_id: 262,
          title: 'Lesson 1',
          subtitle: '',
          order: 0,
          index: '2.1',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '1h 1m',
          content_counts: { assessments: 1 },
          progress: { id: 1775582, status: 'not_started' },
        },
        {
          id: 847,
          stage_id: 262,
          title: 'Lesson 2',
          subtitle: '',
          order: 1,
          index: '2.2',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '1h 1m',
          content_counts: { assessments: 1 },
          progress: { id: 1775584, status: 'not_started' },
        },
        {
          id: 848,
          stage_id: 262,
          title: 'Lesson 3',
          subtitle: '',
          order: 2,
          index: '2.3',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '1h 1m',
          content_counts: { assessments: 1 },
          progress: { id: 1775586, status: 'not_started' },
        },
        {
          id: 849,
          stage_id: 262,
          title: 'Lesson 4',
          subtitle: '',
          order: 3,
          index: '2.4',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '1h 1m',
          content_counts: { assessments: 1 },
          progress: { id: 1775588, status: 'not_started' },
        },
        {
          id: 850,
          stage_id: 262,
          title: 'Lesson 5',
          subtitle: '',
          order: 4,
          index: '2.5',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '1h 1m',
          content_counts: { assessments: 1 },
          progress: { id: 1775590, status: 'not_started' },
        },
        {
          id: 851,
          stage_id: 262,
          title: 'Lesson 6',
          subtitle: '',
          order: 5,
          index: '2.6',
          thumbnail_image_url: '',
          lesson_type: 2,
          completion_time: '1h 1m',
          content_counts: { assessments: 1 },
          progress: { id: 1775592, status: 'not_started' },
        },
      ],
      progress: { id: 1775581, status: 'not_started' },
    },
  ],
  progress: { id: 1775575, status: 'in_progress' },
  enrollments: [
    {
      id: 119056,
      course_version: '2.14',
      enrollment_date: '08/03/22 - present',
      transcript_available: false,
      progress: { id: 1775575, status: PROGRESS_STATUS.in_progress },
      user_certificate: null,
    },
  ],
  next_lesson: {
    id: 846,
    stage_id: 262,
    title: 'Lesson 1',
    subtitle: '',
    order: 0,
    index: '2.1',
    thumbnail_image_url: '',
    lesson_type: 2,
    completion_time: '1h 1m',
    content_counts: { assessments: 1 },
    progress: { id: 1775582, status: 'not_started' },
  },
};

export const course351Completed: ICourseOverview = {
  badge: {
    id: 0,
    name: '',
    desc: '',
    badge_image: '',
    progress: 0,
    isActive: false,
  },
  started_at: '',
  id: 199,
  name: 'Instrument Flight Procedures Course',
  overview:
    'This course is designed to highlight the most important instrument flight techniques and procedures for you as the pilot. As you go through the following videos you’ll discover an informative discussion aimed at optimizing your efficiency and enhancing safety while flying your Cirrus aircraft under IFR.\u003cdiv\u003e\u003cb\u003e\u003cbr\u003e\u003c/b\u003e\u003c/div\u003e\u003cdiv\u003e\u003cb\u003eCourse Time:\u003c/b\u003e\u0026nbsp;2.5 hours (estimate) \u0026nbsp;\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003c/div\u003e',
  major_version: 1,
  minor_version: 16,
  title: 'Instrument Flight Procedures Course',
  subtitle: '',
  has_agreement: false,
  agreement_body: '',
  completion_time: '1h 1m',
  course_attempt: { id: 123456 },
  minimum_flight_hours: 0,
  desktop_hero_image_url: '',
  mobile_hero_image_url: '',
  can_reenroll: true,
  lessons_stats: {
    completed: 0,
    total: 13,
  },
  summary_counts: {
    lessons: 13,
    videos: 13,
  },
  certificate: {
    id: 39,
    expiration: null,
  },
  completed_at: '',
  thumbnail_image_url: '',
  course_content_stats: [
    {
      type: 'self_study',
      completed: 13,
      total: 13,
    },
    {
      type: 'flight_assessment',
      completed: 0,
      total: 0,
    },
    {
      type: 'ground_assessment',
      completed: 0,
      total: 0,
    },
  ],
  hours_and_landings_stats: [
    {
      type: 'completed_total_hours',
      completed: 0.0,
    },
    {
      type: 'completed_ground_instruction_hours',
      completed: 0.0,
    },
    {
      type: 'completed_sim_hours',
      completed: 0.0,
    },
    {
      type: 'completed_cross_country_hours',
      completed: 0.0,
    },
    {
      type: 'completed_total_landings',
      completed: 0.0,
    },
  ],
  stages: [
    {
      id: 7,
      title: 'IFR Departure',
      desc: '',
      overview: '',
      order: 0,
      lessons_are_linear: false,
      lessons: [
        {
          id: 238,
          stage_id: 7,
          title: 'Receive an IFR Clearance',
          subtitle: '',
          order: 0,
          index: '1.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 239,
          stage_id: 7,
          title: 'Loading a Departure Procedure',
          subtitle: '',
          order: 1,
          index: '1.2',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 240,
          stage_id: 7,
          title: 'IFR Takeoff Briefing',
          subtitle: '',
          order: 2,
          index: '1.3',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 241,
          stage_id: 7,
          title: 'IFR Takeoff \u0026 Climb',
          subtitle: '',
          order: 3,
          index: '1.4',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
      ],
      progress: {
        id: 0,
        status: 'completed',
      },
    },
    {
      id: 8,
      title: 'IFR Enroute',
      desc: '',
      overview: '',
      order: 1,
      lessons_are_linear: false,
      lessons: [
        {
          id: 242,
          stage_id: 8,
          title: 'Loading an Airway',
          subtitle: '',
          order: 0,
          index: '2.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 243,
          stage_id: 8,
          title: 'Holding',
          subtitle: '',
          order: 1,
          index: '2.2',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
      ],
      progress: {
        id: 0,
        status: 'completed',
      },
    },
    {
      id: 9,
      title: 'IFR Arrival',
      desc: '',
      overview: '',
      order: 2,
      lessons_are_linear: false,
      lessons: [
        {
          id: 244,
          stage_id: 9,
          title: 'Flying a STAR',
          subtitle: '',
          order: 0,
          index: '3.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 245,
          stage_id: 9,
          title: 'Arrivals \u0026 Vertical Navigation',
          subtitle: '',
          order: 1,
          index: '3.2',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
      ],
      progress: {
        id: 0,
        status: 'completed',
      },
    },
    {
      id: 151,
      title: 'IFR Approach',
      desc: '',
      overview: '',
      order: 3,
      lessons_are_linear: false,
      lessons: [
        {
          id: 246,
          stage_id: 151,
          title: 'Instrument Approach Overview',
          subtitle: '',
          order: 0,
          index: '4.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 247,
          stage_id: 151,
          title: 'VOR Approach',
          subtitle: '',
          order: 1,
          index: '4.2',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 248,
          stage_id: 151,
          title: 'GPS Approach',
          subtitle: '',
          order: 2,
          index: '4.3',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 249,
          stage_id: 151,
          title: 'ILS Approach',
          subtitle: '',
          order: 3,
          index: '4.4',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
        {
          id: 250,
          stage_id: 151,
          title: 'Missed Approach',
          subtitle: '',
          order: 4,
          index: '4.5',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: {
            videos: 1,
          },
          progress: {
            id: 0,
            status: 'completed',
          },
        },
      ],
      progress: {
        id: 0,
        status: 'completed',
      },
    },
  ],
  progress: {
    id: 0,
    status: 'completed',
  },
  enrollments: [
    {
      id: 119065,
      course_version: '1.32',
      enrollment_date: '09/01/22 - present',
      transcript_available: false,
      progress: {
        id: 1775688,
        status: PROGRESS_STATUS.in_progress,
      },
      user_certificate: null,
    },
  ],
  next_lesson: {},
};

export const course466: ICourseOverview = {
  badge: {
    id: 0,
    name: '',
    desc: '',
    badge_image: '',
    progress: 0,
    isActive: false,
  },
  started_at: '',
  id: 466,
  name: 'SR Series Takeoffs and Landings Course',
  overview:
    'Every adventure begins with a takeoff and concludes with a landing - the SR Series Takeoffs and Landings course takes an in-depth look at these everyday procedures to make every takeoff and landing safe, predictable, and repeatable. This course takes a straight-forward practical approach towards each aspect of your takeoff and landing, leaving no detail behind. It puts you behind the controls with fun and instructive 3D graphics, first-person demonstrations by a Cirrus Standardized Instructor Pilot, and the ability to complete each lesson at your own pace.\u003cdiv\u003e\u003cbr\u003e\u003c/div\u003e\u003cdiv\u003e\u003cb\u003eCourse Time:\u003c/b\u003e\u0026nbsp;5.5 hours (estimate)\u003cbr\u003e\u003c/div\u003e',
  major_version: 1,
  minor_version: 2,
  title: 'SR Series Takeoffs and Landings Course',
  subtitle: '',
  has_agreement: false,
  agreement_body: '',
  completion_time: '1h 1m',
  minimum_flight_hours: 0,
  desktop_hero_image_url: '',
  mobile_hero_image_url: '',
  thumbnail_image_url: '',
  can_reenroll: true,
  lessons_stats: { completed: 0, total: 12 },
  summary_counts: { lessons: 12, videos: 50 },
  certificate: { expiration: null },
  completed_at: '',
  course_attempt: { id: 0 },
  course_content_stats: [
    { type: 'self_study', completed: 0, total: 51 },
    { type: 'flight_assessment', completed: 0, total: 0 },
    { type: 'ground_assessment', completed: 0, total: 0 },
  ],
  hours_and_landings_stats: [
    { type: 'completed_total_hours', completed: 0.0 },
    { type: 'completed_ground_instruction_hours', completed: 0.0 },
    { type: 'completed_sim_hours', completed: 0.0 },
    { type: 'completed_cross_country_hours', completed: 0.0 },
    { type: 'completed_total_landings', completed: 0.0 },
  ],
  stages: [
    {
      id: 495,
      title: 'Course Intro',
      desc: '',
      overview: '',
      order: 0,
      lessons_are_linear: false,
      lessons: [
        {
          id: 856,
          stage_id: 495,
          title: 'Your Cirrus Training Edited',
          subtitle: '',
          order: 0,
          index: '1.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '1h 1m',
          content_counts: {},
          progress: { id: 0, status: 'not_started' },
        },
      ],
      progress: { id: 1776118, status: 'not_started' },
    },
    {
      id: 484,
      title: 'SR Series Takeoffs and Landings',
      desc: '',
      overview: '',
      order: 1,
      lessons_are_linear: false,
      lessons: [
        {
          id: 1002,
          stage_id: 484,
          title: 'Intro',
          subtitle: '',
          order: 0,
          index: '2.1',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 1 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1003,
          stage_id: 484,
          title: 'Essential Elements',
          subtitle: '',
          order: 1,
          index: '2.2',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 12 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1004,
          stage_id: 484,
          title: 'Traffic Pattern ',
          subtitle: '',
          order: 2,
          index: '2.3',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1005,
          stage_id: 484,
          title: 'Stabilized Approach',
          subtitle: '',
          order: 3,
          index: '2.4',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 5 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1049,
          stage_id: 484,
          title: 'Faulty Approach',
          subtitle: '',
          order: 4,
          index: '2.5',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1006,
          stage_id: 484,
          title: 'Normal Takeoff and Landing',
          subtitle: '',
          order: 5,
          index: '2.6',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1007,
          stage_id: 484,
          title: 'Crosswinds and Slips',
          subtitle: '',
          order: 6,
          index: '2.7',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1008,
          stage_id: 484,
          title: 'Short-Field Takeoff and Landing',
          subtitle: '',
          order: 7,
          index: '2.8',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 5 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1009,
          stage_id: 484,
          title: 'Soft/Rough-Field Takeoff and Landing',
          subtitle: '',
          order: 8,
          index: '2.9',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1050,
          stage_id: 484,
          title: 'Abnormal/Emergency',
          subtitle: '',
          order: 9,
          index: '2.10',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 4 },
          progress: { id: -1, status: 'not_started' },
        },
        {
          id: 1051,
          stage_id: 484,
          title: 'Night Operations',
          subtitle: '',
          order: 10,
          index: '2.11',
          thumbnail_image_url: '',
          lesson_type: 0,
          completion_time: '',
          content_counts: { videos: 3 },
          progress: { id: -1, status: 'not_started' },
        },
      ],
      progress: { id: 1776121, status: 'not_started' },
    },
  ],
  progress: { id: -1, status: 'not_started' },
  enrollments: [
    {
      id: 119073,
      course_version: '1.10',
      enrollment_date: '09/15/22 - present',
      transcript_available: false,
      progress: { id: 1776117, status: PROGRESS_STATUS.in_progress },
      user_certificate: null,
    },
  ],
  next_lesson: {
    id: 856,
    stage_id: 495,
    title: 'Your Cirrus Training Edited',
    subtitle: '',
    order: 0,
    index: '1.1',
    thumbnail_image_url: '',
    lesson_type: 0,
    completion_time: '',
    content_counts: {},
    progress: { id: -1, status: 'not_started' },
  },
};
