import { ICourseOverviewStage } from '@cirrus/models';
import { findNextLesson } from './find-next-lesson';

const stages351: ICourseOverviewStage[] = [
  {
    id: 243,
    title: 'Course Intro',
    overview: '',
    order: 0,
    lessons_are_linear: false,
    lessons: [
      {
        id: 692,
        title: 'Welcome To Your Cirrus Training',
        order: 0,
        index: '1.1',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { documents: 3 },
        progress: { id: 1775463, status: 'completed' },
      },
    ],
    progress: { id: 1775462, status: 'completed' },
  },
  {
    id: 244,
    title: 'Self Study',
    overview: '',
    order: 1,
    lessons_are_linear: false,
    lessons: [
      {
        id: 857,
        title: 'CAPS',
        order: 0,
        index: '2.1',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { videos: 10 },
        progress: { id: 1775468, status: 'not_started' },
      },
      {
        id: 318,
        title: 'Takeoffs and Landings',
        order: 1,
        index: '2.2',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { videos: 49 },
        progress: { id: 1775479, status: 'not_started' },
      },
      {
        id: 317,
        title: 'Engine Management',
        order: 2,
        index: '2.3',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { videos: 6 },
        progress: { id: 1775529, status: 'not_started' },
      },
      {
        id: 595,
        title: 'Workbook',
        order: 3,
        index: '2.4',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { documents: 3 },
        progress: { id: 1775536, status: 'not_started' },
      },
    ],
    progress: { id: 1775467, status: 'not_started' },
  },
  {
    id: 245,
    title: 'Transition',
    overview: '',
    order: 2,
    lessons_are_linear: false,
    lessons: [
      {
        id: 834,
        title: 'Lesson 1',
        order: 0,
        index: '3.1',
        thumbnail_image_url: '',
        lesson_type: 1,
        completion_time: '1h 1m',
        content_counts: { documents: 1, assessments: 1 },
        progress: { id: 1775541, status: 'not_started' },
      },
      {
        id: 835,
        title: 'Lesson 2',
        order: 1,
        index: '3.2',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775545, status: 'not_started' },
      },
      {
        id: 836,
        title: 'Lesson 3',
        order: 2,
        index: '3.3',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775547, status: 'not_started' },
      },
      {
        id: 837,
        title: 'Lesson 4',
        order: 3,
        index: '3.4',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775549, status: 'not_started' },
      },
      {
        id: 838,
        title: 'Lesson 5',
        order: 4,
        index: '3.5',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775551, status: 'not_started' },
      },
      {
        id: 839,
        title: 'Lesson 6',
        order: 5,
        index: '3.6',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775553, status: 'not_started' },
      },
    ],
    progress: { id: 1775540, status: 'not_started' },
  },
  {
    id: 246,
    title: 'Advanced',
    overview: '',
    order: 3,
    lessons_are_linear: false,
    lessons: [
      {
        id: 840,
        title: 'Lesson 7',
        order: 0,
        index: '4.1',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775556, status: 'not_started' },
      },
      {
        id: 841,
        title: 'Lesson 8',
        order: 1,
        index: '4.2',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775558, status: 'not_started' },
      },
      {
        id: 842,
        title: 'Lesson 9',
        order: 2,
        index: '4.3',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775560, status: 'not_started' },
      },
      {
        id: 843,
        title: 'Lesson 10',
        order: 3,
        index: '4.4',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775562, status: 'not_started' },
      },
    ],
    progress: { id: 1775555, status: 'not_started' },
  },
];

const stages351TwoStagesCompleted: ICourseOverviewStage[] = [
  {
    id: 243,
    title: 'Course Intro',
    overview: '',
    order: 0,
    lessons_are_linear: false,
    lessons: [
      {
        id: 692,
        title: 'Welcome To Your Cirrus Training',
        order: 0,
        index: '1.1',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { documents: 3 },
        progress: { id: 1775463, status: 'completed' },
      },
    ],
    progress: { id: 1775462, status: 'completed' },
  },
  {
    id: 244,
    title: 'Self Study',
    overview: '',
    order: 1,
    lessons_are_linear: false,
    lessons: [
      {
        id: 857,
        title: 'CAPS',
        order: 0,
        index: '2.1',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { videos: 10 },
        progress: { id: 1775468, status: 'completed' },
      },
      {
        id: 318,
        title: 'Takeoffs and Landings',
        order: 1,
        index: '2.2',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { videos: 49 },
        progress: { id: 1775479, status: 'completed' },
      },
      {
        id: 317,
        title: 'Engine Management',
        order: 2,
        index: '2.3',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { videos: 6 },
        progress: { id: 1775529, status: 'completed' },
      },
      {
        id: 595,
        title: 'Workbook',
        order: 3,
        index: '2.4',
        thumbnail_image_url: '',
        lesson_type: 0,
        completion_time: '1h 1m',
        content_counts: { documents: 3 },
        progress: { id: 1775536, status: 'completed' },
      },
    ],
    progress: { id: 1775467, status: 'completed' },
  },
  {
    id: 245,
    title: 'Transition',
    overview: '',
    order: 2,
    lessons_are_linear: false,
    lessons: [
      {
        id: 834,
        title: 'Lesson 1',
        order: 0,
        index: '3.1',
        thumbnail_image_url: '',
        lesson_type: 1,
        completion_time: '1h 1m',
        content_counts: { documents: 1, assessments: 1 },
        progress: { id: 1775541, status: 'completed' },
      },
      {
        id: 835,
        title: 'Lesson 2',
        order: 1,
        index: '3.2',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775545, status: 'not_started' },
      },
      {
        id: 836,
        title: 'Lesson 3',
        order: 2,
        index: '3.3',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775547, status: 'not_started' },
      },
      {
        id: 837,
        title: 'Lesson 4',
        order: 3,
        index: '3.4',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775549, status: 'not_started' },
      },
      {
        id: 838,
        title: 'Lesson 5',
        order: 4,
        index: '3.5',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775551, status: 'not_started' },
      },
      {
        id: 839,
        title: 'Lesson 6',
        order: 5,
        index: '3.6',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775553, status: 'not_started' },
      },
    ],
    progress: { id: 1775540, status: 'not_started' },
  },
  {
    id: 246,
    title: 'Advanced',
    overview: '',
    order: 3,
    lessons_are_linear: false,
    lessons: [
      {
        id: 840,
        title: 'Lesson 7',
        order: 0,
        index: '4.1',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775556, status: 'not_started' },
      },
      {
        id: 841,
        title: 'Lesson 8',
        order: 1,
        index: '4.2',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775558, status: 'not_started' },
      },
      {
        id: 842,
        title: 'Lesson 9',
        order: 2,
        index: '4.3',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775560, status: 'not_started' },
      },
      {
        id: 843,
        title: 'Lesson 10',
        order: 3,
        index: '4.4',
        thumbnail_image_url: '',
        lesson_type: 2,
        completion_time: '1h 1m',
        content_counts: { assessments: 1 },
        progress: { id: 1775562, status: 'not_started' },
      },
    ],
    progress: { id: 1775555, status: 'not_started' },
  },
];

describe('find next lesson helper function', () => {
  it('should be true', () => {
    expect(1 === 1).toBe(true);
  });

  it('should find the next lesson', () => {
    const actual = findNextLesson(stages351);

    expect(actual).toBe(857);
  });
});

describe('find next lesson helper function when given one stage is completed', () => {
  const stages: ICourseOverviewStage[] = [];

  it('should find the next lesson', () => {
    const actual = findNextLesson(stages351TwoStagesCompleted);

    expect(actual).toBe(835);
  });

  it('should find the next lesson when on stage is complete and one stage has a completed lesson', () => {
    const arrangedStages: ICourseOverviewStage[] = [
      {
        id: 244,
        title: 'Self Study',
        overview: '',
        order: 1,
        lessons_are_linear: false,
        lessons: [
          {
            id: 857,
            title: 'CAPS',
            order: 0,
            index: '2.1',
            thumbnail_image_url: '',
            lesson_type: 0,
            completion_time: '1h 1m',
            content_counts: { videos: 10 },
            progress: { id: 1775468, status: 'completed' },
          },
          {
            id: 318,
            title: 'Takeoffs and Landings',
            order: 1,
            index: '2.2',
            thumbnail_image_url: '',
            lesson_type: 0,
            completion_time: '1h 1m',
            content_counts: { videos: 49 },
            progress: { id: 1775479, status: 'completed' },
          },
          {
            id: 317,
            title: 'Engine Management',
            order: 2,
            index: '2.3',
            thumbnail_image_url: '',
            lesson_type: 0,
            completion_time: '1h 1m',
            content_counts: { videos: 6 },
            progress: { id: 1775529, status: 'completed' },
          },
          {
            id: 595,
            title: 'Workbook',
            order: 3,
            index: '2.4',
            thumbnail_image_url: '',
            lesson_type: 0,
            completion_time: '1h 1m',
            content_counts: { documents: 3 },
            progress: { id: 1775536, status: 'completed' },
          },
        ],
        progress: { id: 1775467, status: 'completed' },
      },
      {
        id: 245,
        title: 'Transition',
        overview: '',
        order: 2,
        lessons_are_linear: false,
        lessons: [
          {
            id: 834,
            title: 'Lesson 1',
            order: 0,
            index: '3.1',
            thumbnail_image_url: '',
            lesson_type: 1,
            completion_time: '1h 1m',
            content_counts: { documents: 1, assessments: 1 },
            progress: { id: 1775541, status: 'not_started' },
          },
          {
            id: 835,
            title: 'Lesson 2',
            order: 1,
            index: '3.2',
            thumbnail_image_url: '',
            lesson_type: 2,
            completion_time: '1h 1m',
            content_counts: { assessments: 1 },
            progress: { id: 1775545, status: 'not_started' },
          },
          {
            id: 836,
            title: 'Lesson 3',
            order: 2,
            index: '3.3',
            thumbnail_image_url: '',
            lesson_type: 2,
            completion_time: '1h 1m',
            content_counts: { assessments: 1 },
            progress: { id: 1775547, status: 'not_started' },
          },
          {
            id: 837,
            title: 'Lesson 4',
            order: 3,
            index: '3.4',
            thumbnail_image_url: '',
            lesson_type: 2,
            completion_time: '1h 1m',
            content_counts: { assessments: 1 },
            progress: { id: 1775549, status: 'not_started' },
          },
          {
            id: 838,
            title: 'Lesson 5',
            order: 4,
            index: '3.5',
            thumbnail_image_url: '',
            lesson_type: 2,
            completion_time: '1h 1m',
            content_counts: { assessments: 1 },
            progress: { id: 1775551, status: 'not_started' },
          },
          {
            id: 839,
            title: 'Lesson 6',
            order: 5,
            index: '3.6',
            thumbnail_image_url: '',
            lesson_type: 2,
            completion_time: '1h 1m',
            content_counts: { assessments: 1 },
            progress: { id: 1775553, status: 'not_started' },
          },
        ],
        progress: { id: 1775540, status: 'not_started' },
      },
    ];
    const actual = findNextLesson(arrangedStages);

    expect(actual).toBe(834);
  });

  describe('find next lesson helper function returns 0 when all stages and lessons completed', () => {
    it('should find the next lesson', () => {
      const arrangedStages: ICourseOverviewStage[] = [
        {
          id: 244,
          title: 'Self Study',
          overview: '',
          order: 1,
          lessons_are_linear: false,
          lessons: [
            {
              id: 857,
              title: 'CAPS',
              order: 0,
              index: '2.1',
              thumbnail_image_url: '',
              lesson_type: 0,
              completion_time: '1h 1m',
              content_counts: { videos: 10 },
              progress: { id: 1775468, status: 'completed' },
            },
            {
              id: 318,
              title: 'Takeoffs and Landings',
              order: 1,
              index: '2.2',
              thumbnail_image_url: '',
              lesson_type: 0,
              completion_time: '1h 1m',
              content_counts: { videos: 49 },
              progress: { id: 1775479, status: 'completed' },
            },
            {
              id: 317,
              title: 'Engine Management',
              order: 2,
              index: '2.3',
              thumbnail_image_url: '',
              lesson_type: 0,
              completion_time: '1h 1m',
              content_counts: { videos: 6 },
              progress: { id: 1775529, status: 'completed' },
            },
            {
              id: 595,
              title: 'Workbook',
              order: 3,
              index: '2.4',
              thumbnail_image_url: '',
              lesson_type: 0,
              completion_time: '1h 1m',
              content_counts: { documents: 3 },
              progress: { id: 1775536, status: 'completed' },
            },
          ],
          progress: { id: 1775467, status: 'completed' },
        },
        {
          id: 245,
          title: 'Transition',
          overview: '',
          order: 2,
          lessons_are_linear: false,
          lessons: [
            {
              id: 834,
              title: 'Lesson 1',
              order: 0,
              index: '3.1',
              thumbnail_image_url: '',
              lesson_type: 1,
              completion_time: '1h 1m',
              content_counts: { documents: 1, assessments: 1 },
              progress: { id: 1775541, status: 'completed' },
            },
            {
              id: 835,
              title: 'Lesson 2',
              order: 1,
              index: '3.2',
              thumbnail_image_url: '',
              lesson_type: 2,
              completion_time: '1h 1m',
              content_counts: { assessments: 1 },
              progress: { id: 1775545, status: 'completed' },
            },
            {
              id: 836,
              title: 'Lesson 3',
              order: 2,
              index: '3.3',
              thumbnail_image_url: '',
              lesson_type: 2,
              completion_time: '1h 1m',
              content_counts: { assessments: 1 },
              progress: { id: 1775547, status: 'completed' },
            },
            {
              id: 837,
              title: 'Lesson 4',
              order: 3,
              index: '3.4',
              thumbnail_image_url: '',
              lesson_type: 2,
              completion_time: '1h 1m',
              content_counts: { assessments: 1 },
              progress: { id: 1775549, status: 'completed' },
            },
            {
              id: 838,
              title: 'Lesson 5',
              order: 4,
              index: '3.5',
              thumbnail_image_url: '',
              lesson_type: 2,
              completion_time: '1h 1m',
              content_counts: { assessments: 1 },
              progress: { id: 1775551, status: 'completed' },
            },
            {
              id: 839,
              title: 'Lesson 6',
              order: 5,
              index: '3.6',
              thumbnail_image_url: '',
              lesson_type: 2,
              completion_time: '1h 1m',
              content_counts: { assessments: 1 },
              progress: { id: 1775553, status: 'completed' },
            },
          ],
          progress: { id: 1775540, status: 'completed' },
        },
      ];
      const actual = findNextLesson(arrangedStages);

      expect(actual).toBe(0);
    });
  });

  // const edgeCaseWorkBook: IWorkBook = {
  //   id: 360,
  //   progress: {
  //     id: 1774800,
  //     status: 'in_progress',
  //   },
  //   name: 'Takeoffs & Landings Flight Syllabus',
  //   stages: [
  //     {
  //       id: 494,
  //       order: 0,
  //       name: 'none',
  //       progress: {
  //         id: 1774801,
  //         status: 'completed',
  //       },
  //       lessons: [
  //         {
  //           id: 955,
  //           title: 'Your Cirrus Training',
  //           order: 0,
  //           progress: {
  //             id: 1774802,
  //             status: 'completed',
  //           },
  //           stage_lesson_index: '1.1 Self-Study',
  //         },
  //       ],
  //     },
  //     {
  //       id: 370,
  //       order: 1,
  //       name: 'none',
  //       progress: {
  //         id: 1774806,
  //         status: 'in_progress',
  //       },
  //       lessons: [
  //         {
  //           id: 855,
  //           title: 'Lesson 1',
  //           order: 0,
  //           progress: {
  //             id: 1774807,
  //             status: 'in_progress',
  //           },
  //           stage_lesson_index: '2.1 Flight',
  //         },
  //       ],
  //     },
  //   ],
  // };

  // describe('edge case', () => {
  //   it('should find the next lesson', () => {
  //     const actual = findNextLesson(edgeCaseWorkBook);

  //     expect(actual).toBe(855);
  // });
});
